import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { API_BASE_URL } from '../config/api';
import {
  FaUserTie,
  FaSignOutAlt,
  FaUserCheck,
  FaCalendarAlt,
  FaClock,
  FaEnvelope,
  FaPhoneAlt,
  FaIdBadge,
  FaBuilding,
  FaGraduationCap,
  FaCheckCircle,
  FaTimesCircle,
  FaHourglassHalf,
  FaSearch,
  FaSync,
  FaVideo,
  FaPrint,
  FaPaperPlane,
  FaExclamationTriangle,
  FaFilter,
  FaExternalLinkAlt,
  FaListUl,
  FaUserPlus,
  FaBolt
} from 'react-icons/fa';
import logo from '../assets/logo.webp';

// Dynamic helper to calculate current / upcoming 30-min time slot
const getSuggestedTimeSlot = () => {
  const now = new Date();
  let hours = now.getHours();
  let minutes = now.getMinutes();

  if (minutes < 30) {
    minutes = 30;
  } else {
    hours += 1;
    minutes = 0;
  }

  const formatSlotTime = (h, m) => {
    const period = h >= 12 ? 'PM' : 'AM';
    const displayH = h % 12 === 0 ? 12 : h % 12;
    const displayM = String(m).padStart(2, '0');
    return `${String(displayH).padStart(2, '0')}:${displayM} ${period}`;
  };

  const startStr = formatSlotTime(hours, minutes);
  let endH = hours;
  let endM = minutes + 30;
  if (endM >= 60) {
    endH += 1;
    endM = 0;
  }
  const endStr = formatSlotTime(endH, endM);
  return `${startStr} - ${endStr}`;
};

export default function ReceptionistDashboard({ defaultTab = 'register' }) {
  const navigate = useNavigate();
  const location = useLocation();
  const [currentUser, setCurrentUser] = useState(null);
  const searchParams = new URLSearchParams(location.search);
  const tabQuery = searchParams.get('tab');
  const [activeTab, setActiveTab] = useState(
    location.pathname === '/receptionist/offline-visitor' || tabQuery === 'apply' || tabQuery === 'register'
      ? 'register'
      : tabQuery === 'queue'
      ? 'queue'
      : (defaultTab || 'register')
  );

  // --- Registration Form State ---
  const todayStr = new Date().toISOString().split('T')[0];
  const [visitorName, setVisitorName] = useState('');
  const [visitorPhone, setVisitorPhone] = useState('');
  const [visitorEmail, setVisitorEmail] = useState('');
  const [timeSlot, setTimeSlot] = useState(getSuggestedTimeSlot);
  const [customTime, setCustomTime] = useState('');

  const [registering, setRegistering] = useState(false);
  const [registrationSuccess, setRegistrationSuccess] = useState(null);
  const [registrationError, setRegistrationError] = useState('');

  // --- Queue State ---
  const [queueList, setQueueList] = useState([]);
  const [queueLoading, setQueueLoading] = useState(false);
  const [typeFilter, setTypeFilter] = useState('all'); // 'all', 'offline', 'online'
  const [statusFilter, setStatusFilter] = useState('all'); // 'all', 'pending', 'completed', 'cancelled'
  const [dateFilter, setDateFilter] = useState('all'); // 'today', 'all', 'yesterday', 'last7days'
  const [search, setSearch] = useState('');
  const [stats, setStats] = useState({
    total: 0,
    offline: 0,
    online: 0,
    pending: 0,
    completed: 0,
    cancelled: 0,
    today: 0,
  });

  // Auto-calculated slot number based on today's queue count
  const autoGeneratedSlot = `Slot #${String((stats.today || 0) + 1).padStart(2, '0')}`;

  // Verify authentication
  useEffect(() => {
    const token = localStorage.getItem('adminToken');
    const userStr = localStorage.getItem('adminUser');

    if (!token || !userStr) {
      navigate('/receptionist/login');
      return;
    }

    try {
      const user = JSON.parse(userStr);
      setCurrentUser(user);
    } catch (e) {
      navigate('/receptionist/login');
    }
  }, [navigate]);

  // Fetch Counselling Queue
  const fetchQueue = useCallback(async () => {
    const token = localStorage.getItem('adminToken');
    if (!token) return;

    setQueueLoading(true);
    try {
      const params = new URLSearchParams();
      if (typeFilter !== 'all') params.append('type', typeFilter);
      if (statusFilter !== 'all') params.append('status', statusFilter);
      if (dateFilter !== 'all') params.append('dateFilter', dateFilter);
      if (search.trim()) params.append('search', search.trim());
      params.append('limit', '50');

      const res = await fetch(`${API_BASE_URL}/api/admin/counselling?${params.toString()}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      const data = await res.json();
      if (data.success) {
        setQueueList(data.data || []);
        if (data.stats) {
          setStats(data.stats);
        }
      }
    } catch (err) {
      console.error('Error fetching counselling queue:', err);
    } finally {
      setQueueLoading(false);
    }
  }, [typeFilter, statusFilter, dateFilter, search]);

  useEffect(() => {
    fetchQueue();
  }, [fetchQueue]);

  // Handle Offline Walk-in Registration Submit
  const handleRegisterVisitor = async (e) => {
    e.preventDefault();
    setRegistering(true);
    setRegistrationError('');
    setRegistrationSuccess(null);

    const token = localStorage.getItem('adminToken');
    if (!token) {
      navigate('/receptionist/login');
      return;
    }

    if (!visitorName.trim()) {
      setRegistrationError('Visitor / Student Name is required.');
      setRegistering(false);
      return;
    }

    if (!visitorPhone.trim()) {
      setRegistrationError('Contact Phone Number is required.');
      setRegistering(false);
      return;
    }

    if (!visitorEmail.trim()) {
      setRegistrationError('Visitor Email Address is required.');
      setRegistering(false);
      return;
    }

    const effectiveTime = customTime.trim() ? customTime.trim() : timeSlot;
    if (!effectiveTime) {
      setRegistrationError('Time / Time Slot is required.');
      setRegistering(false);
      return;
    }

    try {
      const payload = {
        name: visitorName.trim(),
        phone: visitorPhone.trim(),
        email: visitorEmail.toLowerCase().trim(),
        date: todayStr,
        timeSlot: effectiveTime,
        slotNumber: autoGeneratedSlot,
        desk: 'Admissions Counseling Desk 1',
        course: 'General Admissions & Counselling',
        notes: '',
      };

      const res = await fetch(`${API_BASE_URL}/api/admin/counselling/offline-walkin`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      });

      const data = await res.json();

      if (data.success) {
        setRegistrationSuccess(data.data);
        // Reset form
        setVisitorName('');
        setVisitorPhone('');
        setVisitorEmail('');
        setCustomTime('');
        setTimeSlot(getSuggestedTimeSlot());
        // Refresh queue & update today's stats for auto slot increment
        fetchQueue();
      } else {
        setRegistrationError(data.message || 'Failed to register visitor.');
      }
    } catch (err) {
      console.error('Registration error:', err);
      setRegistrationError('Network error registering visitor. Please check server connection.');
    } finally {
      setRegistering(false);
    }
  };

  const [updatingId, setUpdatingId] = useState(null);

  // Update appointment status (Pending, Completed, or Cancelled)
  const handleStatusUpdate = async (id, newStatus) => {
    const token = localStorage.getItem('adminToken');
    if (!token) return;

    setUpdatingId(id);

    // Optimistic UI update
    setQueueList((prev) =>
      prev.map((item) => (item._id === id ? { ...item, status: newStatus } : item))
    );

    try {
      const res = await fetch(`${API_BASE_URL}/api/admin/counselling/${id}/status`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ status: newStatus }),
      });

      const data = await res.json();
      if (!data.success) {
        alert(data.message || 'Failed to update status');
        fetchQueue();
      } else {
        // Sync queue and refreshed stats
        fetchQueue();
      }
    } catch (err) {
      console.error('Status update error:', err);
      fetchQueue();
    } finally {
      setUpdatingId(null);
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('adminToken');
    localStorage.removeItem('adminUser');
    navigate('/receptionist/login');
  };

  const printPass = (record) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>AIET Visitor Counselling Pass - ${record.slotNumber || record.token}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 24px; color: #222; }
            .ticket { border: 2px dashed #92400e; border-radius: 12px; padding: 24px; max-width: 500px; margin: 0 auto; background: #fffdf5; }
            .header { text-align: center; border-bottom: 2px solid #b45309; padding-bottom: 12px; margin-bottom: 16px; }
            .header h2 { margin: 0; color: #78350f; font-size: 20px; }
            .header p { margin: 4px 0 0 0; font-size: 12px; color: #666; }
            .slot-highlight { background: #fef3c7; border: 1px solid #f59e0b; padding: 12px; border-radius: 8px; text-align: center; margin-bottom: 16px; }
            .slot-highlight .num { font-size: 26px; font-weight: bold; color: #78350f; }
            .slot-highlight .time { font-size: 14px; color: #b45309; font-weight: 600; margin-top: 4px; }
            .row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #eee; font-size: 13px; }
            .label { color: #666; font-weight: bold; }
            .val { color: #111; }
            .footer { text-align: center; margin-top: 20px; font-size: 11px; color: #777; }
          </style>
        </head>
        <body>
          <div class="ticket">
            <div class="header">
              <h2>Alva's Institute of Engineering & Technology</h2>
              <p>Front Desk & Counselling Center • Shobhavana Campus, Mijar</p>
            </div>
            <div class="slot-highlight">
              <div class="num">${record.slotNumber || 'Confirmed Slot'}</div>
              <div class="time">Reporting Time: ${record.timeSlot || 'During Office Hours'}</div>
            </div>
            <div class="row"><span class="label">Visitor Name:</span><span class="val">${record.name}</span></div>
            <div class="row"><span class="label">Contact Phone:</span><span class="val">${record.phone}</span></div>
            <div class="row"><span class="label">Email:</span><span class="val">${record.email}</span></div>
            <div class="row"><span class="label">Date:</span><span class="val">${record.date}</span></div>
            <div class="row"><span class="label">Assigned Desk:</span><span class="val">${record.desk || 'Reception Desk 1'}</span></div>
            <div class="row"><span class="label">Area of Interest:</span><span class="val">${record.course || 'Admissions'}</span></div>
            <div class="row"><span class="label">Token ID:</span><span class="val"><strong>${record.token}</strong></span></div>
            <div class="footer">
              <p>Please present this slip at the assigned desk.<br>Helpline: +91 8258 262725 | admissions@aiet.org.in</p>
            </div>
          </div>
          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div style={{
      minHeight: '100vh',
      maxWidth: '1400px',
      margin: '0 auto',
      padding: '16px 20px 60px 20px',
      color: '#ffffff',
      boxSizing: 'border-box'
    }}>
      {/* Top Receptionist Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '16px 24px',
        background: 'rgba(15, 15, 15, 0.95)',
        backdropFilter: 'blur(16px)',
        border: '1px solid rgba(255, 204, 0, 0.35)',
        borderRadius: '20px',
        marginBottom: '24px',
        boxShadow: '0 10px 30px rgba(0, 0, 0, 0.6)',
        flexWrap: 'wrap',
        gap: '16px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
          <img src={logo} alt="AIET Logo" style={{ width: '42px', height: '42px', objectFit: 'contain' }} />
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <h1 style={{
                fontSize: '18px',
                fontWeight: '800',
                margin: 0,
                color: '#ffffff',
                letterSpacing: '-0.3px'
              }}>
                AIET Front Desk Counselling Portal
              </h1>
              <span style={{
                background: 'linear-gradient(135deg, rgba(255, 153, 0, 0.2), rgba(255, 85, 0, 0.2))',
                border: '1px solid rgba(255, 204, 0, 0.5)',
                color: '#ffcc00',
                padding: '2px 8px',
                borderRadius: '10px',
                fontSize: '11px',
                fontWeight: '700'
              }}>
                RECEPTION
              </span>
            </div>
            <p style={{ margin: '2px 0 0 0', color: '#a3a3a3', fontSize: '12px' }}>
              Apply Offline Visitors & Real-Time Counselling Management
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
          {currentUser && (
            <div style={{
              background: 'rgba(255, 255, 255, 0.06)',
              border: '1px solid rgba(255, 255, 255, 0.12)',
              padding: '6px 14px',
              borderRadius: '20px',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              fontSize: '13px'
            }}>
              <FaUserTie style={{ color: '#ff9900' }} />
              <div>
                <span style={{ color: '#ffffff', fontWeight: '600' }}>{currentUser.name}</span>
                <span style={{ color: '#ffcc00', marginLeft: '6px', fontSize: '11px' }}>({currentUser.role})</span>
              </div>
            </div>
          )}

          {currentUser?.role !== 'Receptionist' && (
            <button
              type="button"
              onClick={() => navigate('/admin/dashboard')}
              style={{
                background: 'rgba(255, 255, 255, 0.08)',
                border: '1px solid rgba(255, 255, 255, 0.2)',
                color: '#ffffff',
                padding: '8px 16px',
                borderRadius: '14px',
                fontSize: '13px',
                fontWeight: '600',
                cursor: 'pointer'
              }}
            >
              Management Dashboard
            </button>
          )}

          <button
            type="button"
            onClick={handleLogout}
            style={{
              background: 'rgba(220, 38, 38, 0.15)',
              border: '1px solid rgba(220, 38, 38, 0.4)',
              color: '#f87171',
              padding: '8px 16px',
              borderRadius: '14px',
              fontSize: '13px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              transition: 'background 0.2s'
            }}
            onMouseEnter={(e) => (e.currentTarget.style.background = 'rgba(220, 38, 38, 0.3)')}
            onMouseLeave={(e) => (e.currentTarget.style.background = 'rgba(220, 38, 38, 0.15)')}
          >
            <FaSignOutAlt /> Sign Out
          </button>
        </div>
      </div>

      {/* Tabs Selector */}
      <div style={{
        display: 'flex',
        gap: '12px',
        marginBottom: '24px',
        borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
        paddingBottom: '12px'
      }}>
        <button
          type="button"
          onClick={() => setActiveTab('register')}
          style={{
            padding: '11px 24px',
            borderRadius: '12px',
            fontSize: '14px',
            fontWeight: '700',
            cursor: 'pointer',
            border: activeTab === 'register' ? '1.5px solid #ffcc00' : '1px solid rgba(255, 255, 255, 0.12)',
            background: activeTab === 'register'
              ? 'linear-gradient(135deg, rgba(255, 153, 0, 0.3), rgba(255, 85, 0, 0.3))'
              : 'rgba(255, 255, 255, 0.05)',
            color: activeTab === 'register' ? '#ffcc00' : '#d4d4d4',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            transition: 'all 0.2s'
          }}
        >
          <FaUserPlus /> Apply Offline Visitor
        </button>

        <button
          type="button"
          onClick={() => setActiveTab('queue')}
          style={{
            padding: '11px 24px',
            borderRadius: '12px',
            fontSize: '14px',
            fontWeight: '700',
            cursor: 'pointer',
            border: activeTab === 'queue' ? '1.5px solid #ffcc00' : '1px solid rgba(255, 255, 255, 0.12)',
            background: activeTab === 'queue'
              ? 'linear-gradient(135deg, rgba(255, 153, 0, 0.3), rgba(255, 85, 0, 0.3))'
              : 'rgba(255, 255, 255, 0.05)',
            color: activeTab === 'queue' ? '#ffcc00' : '#d4d4d4',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            transition: 'all 0.2s'
          }}
        >
          <FaListUl /> Offline Counselling Queue & Records
          {stats.pending > 0 && (
            <span style={{
              background: '#f59e0b',
              color: '#000000',
              padding: '2px 8px',
              borderRadius: '10px',
              fontSize: '11px',
              fontWeight: '800'
            }}>
              {stats.pending} pending
            </span>
          )}
        </button>
      </div>

      {/* ===================== TAB 1: ON-SPOT REGISTRATION ===================== */}
      {activeTab === 'register' && (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
          gap: '24px',
          alignItems: 'start'
        }}>
          {/* Form Card */}
          <div style={{
            background: 'rgba(20, 20, 20, 0.92)',
            border: '1px solid rgba(255, 204, 0, 0.35)',
            borderRadius: '20px',
            padding: '28px',
            boxShadow: '0 10px 40px rgba(0, 0, 0, 0.5)'
          }}>
            <div style={{ marginBottom: '20px' }}>
              <div style={{
                display: 'inline-block',
                background: 'rgba(255, 204, 0, 0.12)',
                color: '#ffcc00',
                border: '1px solid rgba(255, 204, 0, 0.3)',
                padding: '4px 12px',
                borderRadius: '8px',
                fontSize: '11px',
                fontWeight: '700',
                letterSpacing: '0.8px',
                textTransform: 'uppercase',
                marginBottom: '8px'
              }}>
                Front Desk Counter • Offline Visitor Application
              </div>
              <h2 style={{ fontSize: '22px', fontWeight: '800', margin: '0 0 6px 0', color: '#ffffff' }}>
                Apply Offline Visitor
              </h2>
              <p style={{ margin: 0, color: '#a3a3a3', fontSize: '13px', lineHeight: '1.5' }}>
                Fill in visitor details to register an offline walk-in counselling session. An official confirmation email with the allotted slot number and timing will be dispatched immediately to the visitor.
              </p>
            </div>

            {registrationError && (
              <div style={{
                background: 'rgba(220, 38, 38, 0.15)',
                border: '1px solid rgba(220, 38, 38, 0.5)',
                borderRadius: '12px',
                padding: '12px 14px',
                marginBottom: '20px',
                color: '#f87171',
                fontSize: '13px'
              }}>
                {registrationError}
              </div>
            )}

            {registrationSuccess && (
              <div style={{
                background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.18), rgba(6, 95, 70, 0.25))',
                border: '1.5px solid #10b981',
                borderRadius: '16px',
                padding: '20px',
                marginBottom: '24px',
                boxShadow: '0 8px 30px rgba(16, 185, 129, 0.2)'
              }}>
                <div style={{ marginBottom: '8px' }}>
                  <strong style={{ fontSize: '16px', color: '#ffffff' }}>Visitor Registered Successfully!</strong>
                </div>

                <div style={{
                  display: 'flex',
                  gap: '12px',
                  margin: '12px 0',
                  background: 'rgba(0, 0, 0, 0.3)',
                  padding: '12px 16px',
                  borderRadius: '12px',
                  border: '1px solid rgba(16, 185, 129, 0.3)'
                }}>
                  <div>
                    <span style={{ fontSize: '11px', color: '#a7f3d0', textTransform: 'uppercase', display: 'block' }}>Allotted Slot</span>
                    <strong style={{ fontSize: '18px', color: '#ffcc00' }}>{registrationSuccess.slotNumber}</strong>
                  </div>
                  <div style={{ borderLeft: '1px solid rgba(255, 255, 255, 0.15)', paddingLeft: '12px' }}>
                    <span style={{ fontSize: '11px', color: '#a7f3d0', textTransform: 'uppercase', display: 'block' }}>Allotted Timing</span>
                    <strong style={{ fontSize: '15px', color: '#ffffff' }}>{registrationSuccess.timeSlot}</strong>
                  </div>
                  <div style={{ borderLeft: '1px solid rgba(255, 255, 255, 0.15)', paddingLeft: '12px' }}>
                    <span style={{ fontSize: '11px', color: '#a7f3d0', textTransform: 'uppercase', display: 'block' }}>Token Number</span>
                    <strong style={{ fontSize: '13px', color: '#38bdf8', fontFamily: 'monospace' }}>{registrationSuccess.token}</strong>
                  </div>
                </div>

                <p style={{ margin: '0 0 14px 0', fontSize: '13px', color: '#d1fae5', lineHeight: '1.5' }}>
                  Confirmation email with <strong>{registrationSuccess.slotNumber}</strong>, timing <strong>{registrationSuccess.timeSlot}</strong>, and campus venue directions has been sent to <strong>{registrationSuccess.email}</strong>.
                </p>

                <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                  <button
                    type="button"
                    onClick={() => printPass(registrationSuccess)}
                    style={{
                      background: 'linear-gradient(135deg, #10b981, #059669)',
                      color: '#ffffff',
                      border: 'none',
                      padding: '9px 18px',
                      borderRadius: '10px',
                      fontSize: '13px',
                      fontWeight: '700',
                      cursor: 'pointer',
                      boxShadow: '0 4px 14px rgba(16, 185, 129, 0.4)'
                    }}
                  >
                    Print Token Slip
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setRegistrationSuccess(null);
                      setTimeSlot(getSuggestedTimeSlot());
                      setCustomTime('');
                    }}
                    style={{
                      background: 'rgba(255, 255, 255, 0.1)',
                      color: '#ffffff',
                      border: '1px solid rgba(255, 255, 255, 0.2)',
                      padding: '9px 16px',
                      borderRadius: '10px',
                      fontSize: '13px',
                      fontWeight: '600',
                      cursor: 'pointer'
                    }}
                  >
                    + Register Another Visitor
                  </button>
                </div>
              </div>
            )}

            <form onSubmit={handleRegisterVisitor} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {/* Date & Slot Banner */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))',
                gap: '12px',
                background: 'rgba(255, 255, 255, 0.03)',
                border: '1px solid rgba(255, 204, 0, 0.25)',
                borderRadius: '14px',
                padding: '14px 18px',
              }}>
                <div>
                  <span style={{ fontSize: '11px', color: '#ffcc00', textTransform: 'uppercase', fontWeight: '700', letterSpacing: '0.5px' }}>
                    Date (Today)
                  </span>
                  <div style={{ color: '#ffffff', fontWeight: '700', fontSize: '14px', marginTop: '3px' }}>
                    {new Date().toLocaleDateString('en-IN', { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric' })}
                  </div>
                  <span style={{ fontSize: '11px', color: '#888' }}>{todayStr}</span>
                </div>

                <div>
                  <span style={{ fontSize: '11px', color: '#ffcc00', textTransform: 'uppercase', fontWeight: '700', letterSpacing: '0.5px' }}>
                    Allotted Slot
                  </span>
                  <div style={{ color: '#ffcc00', fontWeight: '800', fontSize: '16px', marginTop: '3px' }}>
                    {autoGeneratedSlot}
                  </div>
                  <span style={{ fontSize: '11px', color: '#10b981', fontWeight: '600' }}>Auto-assigned</span>
                </div>
              </div>

              {/* Row 1: Name & Phone */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '14px' }}>
                <div>
                  <label style={{ display: 'block', color: '#e5e5e5', fontSize: '13px', fontWeight: '600', marginBottom: '6px' }}>
                    Visitor / Student Name *
                  </label>
                  <input
                    type="text"
                    required
                    value={visitorName}
                    onChange={(e) => setVisitorName(e.target.value)}
                    placeholder="Enter full name"
                    style={inputStyle}
                  />
                </div>

                <div>
                  <label style={{ display: 'block', color: '#e5e5e5', fontSize: '13px', fontWeight: '600', marginBottom: '6px' }}>
                    Contact Phone Number *
                  </label>
                  <input
                    type="tel"
                    required
                    value={visitorPhone}
                    onChange={(e) => setVisitorPhone(e.target.value)}
                    placeholder="e.g. 9876543210"
                    style={inputStyle}
                  />
                </div>
              </div>

              {/* Row 2: Email */}
              <div>
                <label style={{ display: 'block', color: '#e5e5e5', fontSize: '13px', fontWeight: '600', marginBottom: '6px' }}>
                  Visitor Email Address * (Confirmation mail will be sent here)
                </label>
                <input
                  type="email"
                  required
                  value={visitorEmail}
                  onChange={(e) => setVisitorEmail(e.target.value)}
                  placeholder="e.g. visitor@gmail.com"
                  style={inputStyle}
                />
              </div>

              {/* Row 3: Time Slot */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                  <label style={{ color: '#e5e5e5', fontSize: '13px', fontWeight: '600' }}>
                    Reporting Time / Time Slot *
                  </label>
                  <button
                    type="button"
                    onClick={() => {
                      setTimeSlot(getSuggestedTimeSlot());
                      setCustomTime('');
                    }}
                    style={{
                      background: 'rgba(255, 204, 0, 0.1)',
                      border: '1px solid rgba(255, 204, 0, 0.3)',
                      color: '#ffcc00',
                      padding: '3px 10px',
                      borderRadius: '6px',
                      fontSize: '11px',
                      fontWeight: '600',
                      cursor: 'pointer'
                    }}
                  >
                    Set Current Time
                  </button>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                  <select
                    value={timeSlot}
                    onChange={(e) => {
                      setTimeSlot(e.target.value);
                      if (e.target.value) setCustomTime('');
                    }}
                    style={selectStyle}
                    required
                  >
                    <option value="09:30 AM - 10:00 AM">09:30 AM - 10:00 AM</option>
                    <option value="10:00 AM - 10:30 AM">10:00 AM - 10:30 AM</option>
                    <option value="10:30 AM - 11:00 AM">10:30 AM - 11:00 AM</option>
                    <option value="11:00 AM - 11:30 AM">11:00 AM - 11:30 AM</option>
                    <option value="11:30 AM - 12:00 PM">11:30 AM - 12:00 PM</option>
                    <option value="12:00 PM - 12:30 PM">12:00 PM - 12:30 PM</option>
                    <option value="02:00 PM - 02:30 PM">02:00 PM - 02:30 PM</option>
                    <option value="02:30 PM - 03:00 PM">02:30 PM - 03:00 PM</option>
                    <option value="03:00 PM - 03:30 PM">03:00 PM - 03:30 PM</option>
                    <option value="03:30 PM - 04:00 PM">03:30 PM - 04:00 PM</option>
                    <option value="04:00 PM - 04:30 PM">04:00 PM - 04:30 PM</option>
                    <option value="Immediate / Walk-in Now">Immediate / Walk-in Now</option>
                  </select>

                  <input
                    type="text"
                    value={customTime}
                    onChange={(e) => setCustomTime(e.target.value)}
                    placeholder="Or enter custom time (e.g. 11:15 AM)"
                    style={inputStyle}
                  />
                </div>
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={registering}
                style={{
                  marginTop: '10px',
                  padding: '14px',
                  background: 'linear-gradient(135deg, #ff9900, #ff5500)',
                  color: '#000000',
                  border: 'none',
                  borderRadius: '12px',
                  fontSize: '15px',
                  fontWeight: '700',
                  cursor: registering ? 'not-allowed' : 'pointer',
                  textAlign: 'center',
                  boxShadow: '0 8px 25px rgba(255, 85, 0, 0.35)',
                  opacity: registering ? 0.7 : 1,
                  transition: 'all 0.2s'
                }}
              >
                {registering ? 'Registering & Sending Confirmation Mail...' : 'Apply Offline Visitor & Dispatch Confirmation Mail'}
              </button>
            </form>
          </div>

          {/* Live Visitor Pass Preview */}
          <div style={{
            background: 'linear-gradient(135deg, rgba(30, 20, 10, 0.8), rgba(20, 20, 20, 0.95))',
            border: '1.5px dashed rgba(255, 204, 0, 0.5)',
            borderRadius: '20px',
            padding: '24px',
            boxShadow: '0 10px 40px rgba(0, 0, 0, 0.5)'
          }}>
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              borderBottom: '1px solid rgba(255, 204, 0, 0.3)',
              paddingBottom: '14px',
              marginBottom: '18px'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <img src={logo} alt="AIET Logo" style={{ width: '32px', height: '32px', objectFit: 'contain' }} />
                <div>
                  <h3 style={{ margin: 0, fontSize: '15px', fontWeight: '800', color: '#ffcc00' }}>
                    VISITOR COUNSELLING PASS
                  </h3>
                  <span style={{ fontSize: '11px', color: '#a3a3a3' }}>AIET Mijar Campus</span>
                </div>
              </div>
              <span style={{
                background: 'rgba(255, 204, 0, 0.15)',
                color: '#ffcc00',
                padding: '4px 10px',
                borderRadius: '12px',
                fontSize: '11px',
                fontWeight: '700'
              }}>
                LIVE PREVIEW
              </span>
            </div>

            {/* Big Slot Badge */}
            <div style={{
              background: 'linear-gradient(135deg, rgba(255, 153, 0, 0.2), rgba(255, 85, 0, 0.2))',
              border: '1.5px solid #ffcc00',
              borderRadius: '14px',
              padding: '16px',
              textAlign: 'center',
              marginBottom: '20px'
            }}>
              <span style={{ fontSize: '11px', color: '#ff9900', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px' }}>
                ALLOCATED COUNSELLING SLOT
              </span>
              <div style={{ fontSize: '28px', fontWeight: '900', color: '#ffcc00', margin: '4px 0' }}>
                {autoGeneratedSlot}
              </div>
              <div style={{ color: '#ffffff', fontSize: '13px', fontWeight: '600' }}>
                {customTime || timeSlot}
              </div>
            </div>

            {/* Details Table */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '13px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '6px' }}>
                <span style={{ color: '#a3a3a3' }}>Visitor Name:</span>
                <strong style={{ color: '#ffffff' }}>{visitorName || 'Rahul Sharma'}</strong>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '6px' }}>
                <span style={{ color: '#a3a3a3' }}>Contact Phone:</span>
                <span style={{ color: '#ffcc00' }}>{visitorPhone || '+91 98765 43210'}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '6px' }}>
                <span style={{ color: '#a3a3a3' }}>Email:</span>
                <span style={{ color: '#ffffff' }}>{visitorEmail || 'visitor@example.com'}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '6px' }}>
                <span style={{ color: '#a3a3a3' }}>Date:</span>
                <span style={{ color: '#ffffff' }}>{todayStr} (Today)</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '6px' }}>
                <span style={{ color: '#a3a3a3' }}>Time:</span>
                <span style={{ color: '#ffcc00', fontWeight: '600' }}>{customTime || timeSlot}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '6px' }}>
                <span style={{ color: '#a3a3a3' }}>Slot Status:</span>
                <span style={{ color: '#10b981', fontWeight: '700' }}>Auto-assigned</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', paddingTop: '4px' }}>
                <span style={{ color: '#a3a3a3' }}>Queue Status:</span>
                <span style={{
                  background: 'rgba(245, 158, 11, 0.2)',
                  color: '#fbbf24',
                  padding: '2px 8px',
                  borderRadius: '8px',
                  fontSize: '11px',
                  fontWeight: '700'
                }}>
                  Pending
                </span>
              </div>
            </div>

            <div style={{
              marginTop: '20px',
              padding: '12px',
              background: 'rgba(255, 255, 255, 0.04)',
              borderRadius: '12px',
              fontSize: '11.5px',
              color: '#888',
              lineHeight: '1.5'
            }}>
              Upon registration, an official AIET confirmation email with this allotted slot ({autoGeneratedSlot}), timing ({customTime || timeSlot}), and campus venue instructions will be automatically dispatched to the visitor's inbox.
            </div>
          </div>
        </div>
      )}

      {/* ===================== TAB 2: QUEUE & STATUS MANAGER ===================== */}
      {activeTab === 'queue' && (
        <div>
          {/* Stats Bar */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))',
            gap: '14px',
            marginBottom: '24px'
          }}>
            <StatCard label="Total Sessions" value={stats.total} icon={<FaListUl />} color="#3b82f6" />
            <StatCard label="Pending Queue" value={stats.pending} icon={<FaHourglassHalf />} color="#f59e0b" />
            <StatCard label="Completed" value={stats.completed} icon={<FaCheckCircle />} color="#10b981" />
            <StatCard label="Cancelled" value={stats.cancelled} icon={<FaTimesCircle />} color="#ef4444" />
            <StatCard label="Offline Walk-ins" value={stats.offline} icon={<FaBuilding />} color="#ff9900" />
            <StatCard label="Online Remote" value={stats.online} icon={<FaVideo />} color="#a855f7" />
          </div>

          {/* Filters Bar */}
          <div style={{
            background: 'rgba(20, 20, 20, 0.95)',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            borderRadius: '18px',
            padding: '16px 20px',
            marginBottom: '20px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '14px',
            flexWrap: 'wrap'
          }}>
            {/* Search */}
            <div style={{ position: 'relative', flex: '1 1 240px', maxWidth: '360px' }}>
              <FaSearch style={{ position: 'absolute', left: '14px', top: '50%', transform: 'translateY(-50%)', color: '#888' }} />
              <input
                type="text"
                placeholder="Search visitor, phone, token, slot..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                style={{
                  width: '100%',
                  padding: '9px 14px 9px 38px',
                  background: 'rgba(255, 255, 255, 0.05)',
                  border: '1px solid rgba(255, 255, 255, 0.15)',
                  borderRadius: '10px',
                  color: '#ffffff',
                  fontSize: '13px',
                  outline: 'none',
                  boxSizing: 'border-box'
                }}
              />
            </div>

            {/* Filter Pills */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
              {/* Type Filter */}
              <div style={{ display: 'flex', background: 'rgba(255, 255, 255, 0.06)', borderRadius: '10px', padding: '3px' }}>
                <FilterButton active={typeFilter === 'all'} onClick={() => setTypeFilter('all')}>All</FilterButton>
                <FilterButton active={typeFilter === 'offline'} onClick={() => setTypeFilter('offline')}>Offline</FilterButton>
                <FilterButton active={typeFilter === 'online'} onClick={() => setTypeFilter('online')}>Online</FilterButton>
              </div>

              {/* Status Filter */}
              <div style={{ display: 'flex', background: 'rgba(255, 255, 255, 0.06)', borderRadius: '10px', padding: '3px' }}>
                <FilterButton active={statusFilter === 'all'} onClick={() => setStatusFilter('all')}>All</FilterButton>
                <FilterButton active={statusFilter === 'pending'} onClick={() => setStatusFilter('pending')}>Pending</FilterButton>
                <FilterButton active={statusFilter === 'completed'} onClick={() => setStatusFilter('completed')}>Completed</FilterButton>
                <FilterButton active={statusFilter === 'cancelled'} onClick={() => setStatusFilter('cancelled')}>Cancelled</FilterButton>
              </div>

              {/* Date Filter */}
              <select
                value={dateFilter}
                onChange={(e) => setDateFilter(e.target.value)}
                style={{
                  background: 'rgba(255, 255, 255, 0.06)',
                  border: '1px solid rgba(255, 255, 255, 0.15)',
                  color: '#ffffff',
                  padding: '7px 12px',
                  borderRadius: '10px',
                  fontSize: '12px',
                  outline: 'none'
                }}
              >
                <option value="all">All Dates</option>
                <option value="today">Today Only</option>
                <option value="yesterday">Yesterday</option>
                <option value="last7days">Last 7 Days</option>
              </select>

              <button
                type="button"
                onClick={fetchQueue}
                title="Refresh Queue"
                style={{
                  background: 'rgba(255, 204, 0, 0.1)',
                  border: '1px solid rgba(255, 204, 0, 0.3)',
                  color: '#ffcc00',
                  padding: '8px 14px',
                  borderRadius: '10px',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  fontSize: '12px',
                  fontWeight: '600'
                }}
              >
                <FaSync style={{ animation: queueLoading ? 'spin 1s linear infinite' : 'none' }} /> Refresh
              </button>

              <button
                type="button"
                onClick={() => setActiveTab('register')}
                title="Open Offline Visitor Application Form"
                style={{
                  background: 'linear-gradient(135deg, #ff9900, #ff5500)',
                  color: '#000000',
                  border: 'none',
                  padding: '8px 16px',
                  borderRadius: '10px',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  fontSize: '12px',
                  fontWeight: '700',
                  boxShadow: '0 4px 15px rgba(255, 153, 0, 0.3)'
                }}
              >
                <FaUserPlus /> Apply Offline Visitor
              </button>
            </div>
          </div>

          {/* Counselling Queue Table */}
          <div style={{
            background: 'rgba(20, 20, 20, 0.95)',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            borderRadius: '20px',
            overflow: 'hidden',
            boxShadow: '0 10px 40px rgba(0, 0, 0, 0.5)'
          }}>
            {queueLoading && queueList.length === 0 ? (
              <div style={{ padding: '60px 20px', textAlign: 'center', color: '#ffcc00' }}>
                <FaSync style={{ animation: 'spin 1s linear infinite', fontSize: '24px', marginBottom: '12px' }} />
                <p style={{ margin: 0, fontSize: '14px' }}>Loading counselling sessions...</p>
              </div>
            ) : queueList.length === 0 ? (
              <div style={{ padding: '60px 20px', textAlign: 'center', color: '#a3a3a3' }}>
                <FaHourglassHalf style={{ fontSize: '32px', marginBottom: '12px', color: '#ff9900' }} />
                <h3 style={{ margin: '0 0 6px 0', color: '#ffffff' }}>No Counselling Appointments Found</h3>
                <p style={{ margin: '0 0 16px 0', fontSize: '13px' }}>
                  No sessions match the selected filters. Use the "Apply Offline Visitor" page to register walk-in visitors.
                </p>
                <button
                  type="button"
                  onClick={() => setActiveTab('register')}
                  style={{
                    padding: '10px 20px',
                    background: 'linear-gradient(135deg, #ff9900, #ff5500)',
                    color: '#000000',
                    border: 'none',
                    borderRadius: '10px',
                    fontSize: '13px',
                    fontWeight: '700',
                    cursor: 'pointer',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '6px',
                    boxShadow: '0 4px 15px rgba(255, 153, 0, 0.3)'
                  }}
                >
                  <FaUserPlus /> Apply Offline Visitor
                </button>
              </div>
            ) : (
              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '13px' }}>
                  <thead>
                    <tr style={{
                      background: 'rgba(255, 255, 255, 0.04)',
                      borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
                      color: '#ffcc00',
                      textTransform: 'uppercase',
                      fontSize: '11px',
                      letterSpacing: '0.8px'
                    }}>
                      <th style={{ padding: '14px 18px' }}>Slot / Token</th>
                      <th style={{ padding: '14px 18px' }}>Visitor Details</th>
                      <th style={{ padding: '14px 18px' }}>Type & Meet</th>
                      <th style={{ padding: '14px 18px' }}>Date & Timing</th>
                      <th style={{ padding: '14px 18px' }}>Desk / Branch</th>
                      <th style={{ padding: '14px 18px' }}>Status</th>
                      <th style={{ padding: '14px 18px', textAlign: 'center' }}>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {queueList.map((item) => {
                      const isPending = item.status === 'pending' || !item.status;
                      const isCompleted = item.status === 'completed';
                      const isCancelled = item.status === 'cancelled';

                      return (
                        <tr
                          key={item._id}
                          style={{
                            borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
                            transition: 'background 0.15s'
                          }}
                          onMouseEnter={(e) => (e.currentTarget.style.background = 'rgba(255, 255, 255, 0.02)')}
                          onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                        >
                          {/* Slot & Token */}
                          <td style={{ padding: '14px 18px', whiteSpace: 'nowrap' }}>
                            <div style={{
                              display: 'inline-block',
                              background: 'rgba(255, 204, 0, 0.12)',
                              color: '#ffcc00',
                              border: '1px solid rgba(255, 204, 0, 0.35)',
                              padding: '3px 8px',
                              borderRadius: '8px',
                              fontWeight: '800',
                              fontSize: '12px',
                              marginBottom: '3px'
                            }}>
                              {item.slotNumber || `Slot #${item.queueNumber || '1'}`}
                            </div>
                            <div style={{ color: '#888', fontSize: '11px', fontFamily: 'monospace' }}>
                              {item.token}
                            </div>
                          </td>

                          {/* Visitor Name & Contact */}
                          <td style={{ padding: '14px 18px' }}>
                            <div style={{ fontWeight: '700', color: '#ffffff', fontSize: '14px' }}>
                              {item.name}
                            </div>
                            <div style={{ display: 'flex', gap: '12px', marginTop: '3px', fontSize: '12px' }}>
                              <a
                                href={`tel:${item.phone}`}
                                style={{ color: '#ff9900', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '4px' }}
                              >
                                <FaPhoneAlt style={{ fontSize: '10px' }} /> {item.phone}
                              </a>
                              <a
                                href={`mailto:${item.email}`}
                                style={{ color: '#93c5fd', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '4px' }}
                              >
                                <FaEnvelope style={{ fontSize: '10px' }} /> {item.email}
                              </a>
                            </div>
                          </td>

                          {/* Type */}
                          <td style={{ padding: '14px 18px', whiteSpace: 'nowrap' }}>
                            {item.type === 'offline' ? (
                              <span style={{
                                background: 'rgba(255, 153, 0, 0.12)',
                                color: '#ff9900',
                                border: '1px solid rgba(255, 153, 0, 0.3)',
                                padding: '4px 10px',
                                borderRadius: '12px',
                                fontSize: '11px',
                                fontWeight: '700',
                                display: 'inline-flex',
                                alignItems: 'center',
                                gap: '5px'
                              }}>
                                <FaBuilding /> Offline Campus
                              </span>
                            ) : (
                              <div>
                                <span style={{
                                  background: 'rgba(168, 85, 247, 0.12)',
                                  color: '#c084fc',
                                  border: '1px solid rgba(168, 85, 247, 0.3)',
                                  padding: '4px 10px',
                                  borderRadius: '12px',
                                  fontSize: '11px',
                                  fontWeight: '700',
                                  display: 'inline-flex',
                                  alignItems: 'center',
                                  gap: '5px'
                                }}>
                                  <FaVideo /> Online Video
                                </span>
                                {item.virtualLink && (
                                  <div style={{ marginTop: '4px' }}>
                                    <a
                                      href={item.virtualLink}
                                      target="_blank"
                                      rel="noreferrer"
                                      style={{ color: '#60a5fa', fontSize: '11px', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '3px' }}
                                    >
                                      Join Meet <FaExternalLinkAlt style={{ fontSize: '9px' }} />
                                    </a>
                                  </div>
                                )}
                              </div>
                            )}
                          </td>

                          {/* Date & Timing */}
                          <td style={{ padding: '14px 18px', whiteSpace: 'nowrap' }}>
                            <div style={{ color: '#ffffff', fontWeight: '600' }}>{item.date}</div>
                            <div style={{ color: '#ffcc00', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '4px', marginTop: '2px' }}>
                              <FaClock style={{ fontSize: '11px' }} />
                              {item.timeSlot || 'Scheduled Time'}
                            </div>
                          </td>

                          {/* Desk & Branch */}
                          <td style={{ padding: '14px 18px' }}>
                            <div style={{ color: '#ffffff', fontSize: '12px' }}>{item.desk || 'Admissions Desk'}</div>
                            <div style={{ color: '#a3a3a3', fontSize: '11px', marginTop: '2px' }}>{item.course || 'Admissions'}</div>
                          </td>

                          {/* Status Badge / Interactive Dropdown */}
                          <td style={{ padding: '14px 18px', whiteSpace: 'nowrap' }}>
                            <div style={{ position: 'relative', display: 'inline-block' }}>
                              <select
                                value={item.status || 'pending'}
                                onChange={(e) => handleStatusUpdate(item._id, e.target.value)}
                                disabled={updatingId === item._id}
                                title="Click to change appointment status"
                                style={{
                                  background:
                                    item.status === 'completed'
                                      ? 'rgba(16, 185, 129, 0.18)'
                                      : item.status === 'cancelled'
                                      ? 'rgba(239, 68, 68, 0.18)'
                                      : 'rgba(245, 158, 11, 0.18)',
                                  color:
                                    item.status === 'completed'
                                      ? '#34d399'
                                      : item.status === 'cancelled'
                                      ? '#f87171'
                                      : '#fbbf24',
                                  border: `1px solid ${
                                    item.status === 'completed'
                                      ? 'rgba(16, 185, 129, 0.5)'
                                      : item.status === 'cancelled'
                                      ? 'rgba(239, 68, 68, 0.5)'
                                      : 'rgba(245, 158, 11, 0.5)'
                                  }`,
                                  borderRadius: '12px',
                                  padding: '5px 12px',
                                  fontSize: '12px',
                                  fontWeight: '700',
                                  cursor: updatingId === item._id ? 'wait' : 'pointer',
                                  outline: 'none',
                                  transition: 'all 0.2s',
                                  boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)'
                                }}
                              >
                                <option value="pending" style={{ background: '#18181b', color: '#fbbf24' }}>
                                  Pending
                                </option>
                                <option value="completed" style={{ background: '#18181b', color: '#34d399' }}>
                                  Completed
                                </option>
                                <option value="cancelled" style={{ background: '#18181b', color: '#f87171' }}>
                                  Cancelled
                                </option>
                              </select>
                            </div>
                          </td>

                          {/* Quick Actions */}
                          <td style={{ padding: '14px 18px', textAlign: 'center', whiteSpace: 'nowrap' }}>
                            <div style={{ display: 'inline-flex', gap: '6px', alignItems: 'center' }}>
                              {/* 1-Click to Pending (if not pending) */}
                              {item.status !== 'pending' && (
                                <button
                                  type="button"
                                  disabled={updatingId === item._id}
                                  onClick={() => handleStatusUpdate(item._id, 'pending')}
                                  title="Change status to Pending"
                                  style={{
                                    background: 'rgba(245, 158, 11, 0.15)',
                                    color: '#fbbf24',
                                    border: '1px solid rgba(245, 158, 11, 0.4)',
                                    padding: '6px 10px',
                                    borderRadius: '8px',
                                    fontSize: '11px',
                                    fontWeight: '700',
                                    cursor: updatingId === item._id ? 'wait' : 'pointer',
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    gap: '4px',
                                    transition: 'all 0.2s'
                                  }}
                                >
                                  <FaHourglassHalf style={{ fontSize: '10px' }} /> Pending
                                </button>
                              )}

                              {/* 1-Click to Completed (if not completed) */}
                              {item.status !== 'completed' && (
                                <button
                                  type="button"
                                  disabled={updatingId === item._id}
                                  onClick={() => handleStatusUpdate(item._id, 'completed')}
                                  title="Mark as Completed"
                                  style={{
                                    background: 'linear-gradient(135deg, #10b981, #059669)',
                                    color: '#ffffff',
                                    border: 'none',
                                    padding: '6px 12px',
                                    borderRadius: '8px',
                                    fontSize: '11px',
                                    fontWeight: '700',
                                    cursor: updatingId === item._id ? 'wait' : 'pointer',
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    gap: '4px',
                                    transition: 'all 0.2s',
                                    boxShadow: '0 2px 8px rgba(16, 185, 129, 0.3)'
                                  }}
                                >
                                  <FaCheckCircle style={{ fontSize: '11px' }} /> Complete
                                </button>
                              )}

                              {/* 1-Click to Cancelled (if not cancelled) */}
                              {item.status !== 'cancelled' && (
                                <button
                                  type="button"
                                  disabled={updatingId === item._id}
                                  onClick={() => handleStatusUpdate(item._id, 'cancelled')}
                                  title="Cancel Appointment"
                                  style={{
                                    background: 'rgba(239, 68, 68, 0.15)',
                                    color: '#f87171',
                                    border: '1px solid rgba(239, 68, 68, 0.4)',
                                    padding: '6px 10px',
                                    borderRadius: '8px',
                                    fontSize: '11px',
                                    fontWeight: '700',
                                    cursor: updatingId === item._id ? 'wait' : 'pointer',
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    gap: '4px',
                                    transition: 'all 0.2s'
                                  }}
                                >
                                  <FaTimesCircle style={{ fontSize: '11px' }} /> Cancel
                                </button>
                              )}

                              {item.type === 'offline' && (
                                <button
                                  type="button"
                                  onClick={() => printPass(item)}
                                  title="Print Visitor Pass Slip"
                                  style={{
                                    background: 'rgba(255, 204, 0, 0.1)',
                                    color: '#ffcc00',
                                    border: '1px solid rgba(255, 204, 0, 0.3)',
                                    padding: '6px 8px',
                                    borderRadius: '8px',
                                    fontSize: '12px',
                                    cursor: 'pointer',
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    transition: 'all 0.2s'
                                  }}
                                >
                                  <FaPrint />
                                </button>
                              )}
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// Subcomponents
function StatCard({ label, value, icon, color }) {
  return (
    <div style={{
      background: 'rgba(20, 20, 20, 0.85)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '16px',
      padding: '16px 18px',
      display: 'flex',
      alignItems: 'center',
      gap: '14px',
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.4)'
    }}>
      <div style={{
        width: '42px',
        height: '42px',
        borderRadius: '12px',
        background: `${color}20`,
        color: color,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '18px',
        flexShrink: 0
      }}>
        {icon}
      </div>
      <div>
        <div style={{ fontSize: '20px', fontWeight: '800', color: '#ffffff' }}>
          {value}
        </div>
        <div style={{ fontSize: '11.5px', color: '#a3a3a3', fontWeight: '600' }}>
          {label}
        </div>
      </div>
    </div>
  );
}

function FilterButton({ active, onClick, children }) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        background: active ? 'linear-gradient(135deg, #ff9900, #ff5500)' : 'transparent',
        color: active ? '#000000' : '#d4d4d4',
        border: 'none',
        padding: '5px 12px',
        borderRadius: '8px',
        fontSize: '12px',
        fontWeight: active ? '700' : '500',
        cursor: 'pointer',
        transition: 'all 0.15s'
      }}
    >
      {children}
    </button>
  );
}

const inputStyle = {
  width: '100%',
  padding: '12px 14px',
  background: 'rgba(255, 255, 255, 0.05)',
  border: '1px solid rgba(255, 255, 255, 0.15)',
  borderRadius: '10px',
  color: '#ffffff',
  fontSize: '14px',
  outline: 'none',
  boxSizing: 'border-box'
};

const selectStyle = {
  width: '100%',
  padding: '12px 14px',
  background: '#1a1a1a',
  border: '1px solid rgba(255, 255, 255, 0.15)',
  borderRadius: '10px',
  color: '#ffffff',
  fontSize: '14px',
  outline: 'none',
  boxSizing: 'border-box'
};
