import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    // Navbar
    nav_college_name: "Alva's Institute Of Engineering & Technology",
    nav_home: "Home",
    nav_virtual_tour: "Virtual Tour",
    nav_placements: "Placements",
    nav_research: "Research",
    nav_vision: "Vision & Mission",
    nav_contact: "Contact Us",
    nav_programs: "UG/PG Programs",
    nav_apply: "Apply Now",
    nav_back: "Back",
    nav_ug_adm: "UG Admissions",
    nav_pg_adm: "PG Admissions",
    nav_admin: "Admin",
    nav_admin_portal: "Admin Portal",

    // Hero
    hero_badge: "ALVA'S INSTITUTE OF ENGINEERING & TECHNOLOGY",
    hero_autonomous: "(An Autonomous Institute)",
    hero_title_1: "REDEFINING",
    hero_title_2: "TECHNICAL & MANAGEMENT EDUCATION",
    hero_title_highlight: "ENGINEERING",
    hero_title_suffix: "& MANAGEMENT",
    hero_sub_heading: "Seat Booking and Offline/Online Counseling Booking",
    hero_subtitle: "Explore every block with immersive 360° virtual tours, discover departments, check placements, faculty information, and admission details—all in one place.",
    hero_btn_primary: "Explore Campus →",
    hero_btn_secondary: "Watch Demo",

    // Stats
    stats_title: "Milestones",
    stats_subtitle: "Verifiable milestones representing institutional excellence and career results.",
    stats_rank_label: "Times Engineering Rank in India",
    stats_rank_desc: "18th Best Engineering Institution in Karnataka",
    stats_outlook_label: "Outlook-ICARE Rank in India",
    stats_outlook_desc: "Ranked #53 Top Private Engineering Colleges in India",
    stats_grade_label: "NAAC Accreditation Metric",
    stats_grade_desc: "NBA Certified Core Tech Programs (CSE & ECE)",
    stats_shortlist_label: "Shortlisted at Alva's Pragati",
    stats_shortlist_desc: "Via Coastal Karnataka's Largest Mega Placement Drive",
    stats_partners_label: "Hiring Corporate Partners",
    stats_partners_desc: "Active Recruiters Visiting Mijar Campus Footprint",
    stats_news_btn: "Alva's News letter",

    // Placements
    place_title: "Placement Records",
    place_subtitle: "Verifiable career statistics from our dedicated Training & Placement Cell.",
    place_high_ctc: "Highest CTC Pack",
    place_high_desc: "Bagged at Visa",
    place_sec_ctc: "Second Highest",
    place_sec_desc: "Bagged at Juspay",
    place_avg_ctc: "Average Metric",
    place_avg_desc: "Institutional Base",
    place_corp: "Corporate Partners",
    place_corp_desc: "Active Recruitment",
    place_prom_title: "Prominent Hiring Partners",
    place_prom_subtitle: "Firms actively picking technical talent directly from our Mijar campus footprint.",
    place_recent_milestones: "Recent Placement Milestones",
    place_why_aiet: "Why AIET is a Preferred Destination for Training & Placement",
    place_view_posters: "View Recent Placement Milestones (27 Posters)",
    place_click_poster: "Click any poster to inspect details in full resolution",
    place_view_all_partners: "View All Hiring Partners (156+ Companies)",
    place_modal_subtitle: "Explore all 156+ corporate recruiters hiring from AIET campus drives",
    place_recent_subtitle: "Explore student placement offers, corporate hiring posters, and campus recruitment highlights.",
    place_ecosystem_subtitle: "AIET’s dedicated placement ecosystem focuses on maximizing career opportunities for every student.",
    place_feat_1: "Advanced pre-placement technical training programs from 2nd year.",
    place_feat_2: "Technical skill development workshops",
    place_feat_3: "Soft skills and personality enhancement sessions right from 1st semester",
    place_feat_4: "Internship opportunities with PPO offers ranging from 6LPA-36LPA",
    place_feat_5: "On-campus and off-campus recruitment drives",
    place_feat_6: "Pool campus and mass hiring events",
    place_feat_7: "Resume building and LinkedIn profile optimization",
    place_feat_8: "Mock interviews from industry professionals, aptitude training, and HR preparation",
    place_feat_9: "Guidance from company professionals including the professionals at the in-house Technology Centre",

    // Faculty
    fac_title: "Expert Faculty Profiles",
    fac_subtitle: "Learn from academic mentors leading research and engineering innovation.",
    fac_dept_all: "All Departments",
    fac_dept_admin: "Administration",
    fac_dept_cse: "Computer Science & Eng.",
    fac_dept_ise: "Information Science & Eng.",
    fac_dept_ece: "Electronics & Comm. Eng.",
    fac_dept_civil: "Civil Engineering",
    fac_dept_me: "Mechanical Engineering",
    fac_dept_aiml: "AI & Machine Learning",
    fac_dept_aids: "AI & Data Science",
    fac_dept_csd: "Computer Science & Design",
    fac_dept_iot: "IoT & Cyber Security",
    fac_dept_mba: "Master of Business Administration (MBA)",
    fac_dept_ug: "Undergraduate (UG)",
    fac_dept_pg: "Postgraduate (PG)",
    fac_role_prin: "Principal & Professor",
    fac_role_prof_hod: "Professor & HOD",
    fac_role_assoc: "Associate Professor",
    fac_role_assist: "Assistant Professor",
    fac_role_snr_assist: "Senior Assistant Professor",
    fac_role_adm_off: "Admissions Officer",

    // Contact
    contact_title: "Contact Administration",
    contact_subtitle: "Reach out directly to the official Alva's Admissions Desk.",
    contact_loc_title: "Campus Location",
    contact_loc_desc: "Shobhavana Campus, Mijar, Moodbidri, Dakshina Kannada, Karnataka - 574225",
    contact_loc_link: "Open in Google Maps →",
    contact_hotline_title: "Admissions Office Hotlines",
    contact_call_now: "[Call Now]",
    contact_mail_title: "Electronic Desk",
    contact_mail_link: "Open Mail Inbox →",
    contact_form_title: "Send an Immediate Enquiry",
    contact_form_name: "Your Name",
    contact_form_email: "Your Email",
    contact_form_msg: "Type your query regarding courses, fees, or hostel availability...",
    contact_form_btn: "Dispatch Query",
    contact_status_sending: "Dispatching enquiry...",
    contact_status_success: "🎉 Enquiry dispatched successfully!",
    contact_status_fail: "❌ Dispatch failed:",
    contact_status_error: "❌ Network error connecting to backend.",

    // Features
    feat_title: "Campus Amenities & Facilities",
    feat_subtitle: "Discover campus facilities thoughtfully designed for student development.",
    btn_preview: "Preview",
    feat_hostel_title: "College Hostel",
    feat_hostel_desc: "Separate boys and girls hostels with 24/7 security and hygienic environment.",
    feat_food_title: "Hostel Mess",
    feat_food_desc: "Hygienic and nutritious veg & non-veg meals served daily.",
    feat_sports_title: "Sports Grounds",
    feat_sports_desc: "Extensive playfields for sports and athletics training.",
    feat_badm_title: "Badminton Courts",
    feat_badm_desc: "Professional indoor badminton courts for training and games.",
    feat_swim_title: "Swimming Pool",
    feat_swim_desc: "Clean and well-maintained swimming pool for training and recreation.",
    feat_clubs_title: "40+ Active Clubs",
    feat_clubs_desc: "Over 40 clubs for technical, cultural, and social activities.",
    feat_ncc_title: "NCC Corps",
    feat_ncc_desc: "NCC unit building discipline and leadership.",
    feat_gym_title: "Fitness Gymnasium",
    feat_gym_desc: "Gym equipped with modern workout machines and trainers.",
    feat_shoba_title: "Shobhavana Campus",
    feat_shoba_desc: "Lush green eco-friendly campus providing serene learning environment.",
    feat_medical_title: "Medical Facility",
    feat_medical_desc: "24/7 health center with medical staff and ambulance service.",
    feat_bus_title: "College Transport",
    feat_bus_desc: "Safe college bus transport connecting major routes.",
    feat_campus_main_title: "Main Campus Buildings",
    feat_campus_main_desc: "Lush green surrounding main academic and administrative blocks.",
    feat_hostel_room_title: "Hostel Rooms",
    feat_hostel_room_desc: "Furnished rooms with study table, wardrobe, and Wi-Fi.",
    feat_park_title: "Green Parks",
    feat_park_desc: "Beautiful green parks for relaxation and outdoor study.",
    feat_stationary_title: "Stationery Shop",
    feat_stationary_desc: "On-campus stationery store for daily student requirements.",
    feat_foodcourt_title: "Food Court",
    feat_foodcourt_desc: "Hygienic food court offering delicious meals and snacks.",
    feat_kudla_title: "Kudla Military Hotel",
    feat_kudla_desc: "Fresh and authentic local non-veg cuisine.",
    feat_kitchen_title: "Kitchen Express",
    feat_kitchen_desc: "Quick bites, snacks, and refreshing beverages.",
    feat_ac_class_title: "AC Classrooms",
    feat_ac_class_desc: "Air-conditioned classrooms equipped with digital teaching aids.",
    feat_lift_title: "Campus Elevators",
    feat_lift_desc: "High-speed lifts across all buildings for easy navigation.",
    feat_campus_sel_title: "Campus Selections",
    feat_campus_sel_desc: "Placement cell facilitating top tier corporate career drives.",
    feat_adv_lab_title: "Advanced Laboratories",
    feat_adv_lab_desc: "High-tech labs equipped with modern software and hardware.",
    feat_lib_title: "College Library",
    feat_lib_desc: "Serene library hall equipped with extensive book collections and digital e-learning.",
    feat_atm_title: "Campus ATM",
    feat_atm_desc: "24/7 ATM facility inside the campus.",
    feat_trainer_title: "Our Startups & Industrial In-House",
    feat_trainer_desc: "Industry experts training students for job-readiness.",
    feat_startups_title: "Our Startups",
    feat_startups_desc: "Student and alumni startups and technological innovations.",
    feat_industrial_title: "Industrial In-House",
    feat_industrial_desc: "Industry-partnered skill hubs and training centers on campus.",
    feat_events_title: "College Events & Cultural Fests",
    feat_events_desc: "Annual cultural fests, tech expos, hackathons, and sports meets.",
    feat_co_infosys_title: "Infosys",
    feat_co_infosys_desc: "Global leader in next-generation digital services and consulting.",
    feat_co_stellium_title: "Stellium",
    feat_co_stellium_desc: "Specialized in supply chain, analytics, and business transformation.",
    feat_co_kakunje_title: "Kakunje Software",
    feat_co_kakunje_desc: "Innovative software solutions and IT consulting services.",
    feat_co_metasoft_title: "Metasoft",
    feat_co_metasoft_desc: "Delivering high quality software development and engineering solutions.",
    feat_co_strae_title: "StraeCon",
    feat_co_strae_desc: "Strategic consulting and advanced IT infrastructure services.",
    feat_co_toyota_title: "Toyota & Bosch Skill Development Labs",
    feat_co_toyota_desc: "In-house industrial technical training units equipped with automotive cut-sections, robotics, and advanced automation kits.",
    feat_startup_modal_title: "E-Cell AIET & Technology Center Foundation Incubated Startups",
    label_founder: "FOUNDER:",
    btn_visit_website: "VISIT WEBSITE",

    // Sports Grounds Modal Keys
    feat_sports_modal_title: "Sports Grounds & Athletic Facilities",
    feat_sports_pool_title: "Swimming Pool Complex",
    feat_sports_pool_desc: "Standard Olympic-size swimming pool facility equipped with modern water filtration systems, professional coaches, lifeguards, and competitive racing lanes.",
    feat_sports_badm_title: "Badminton Complex",
    feat_sports_badm_desc: "High-ceiling indoor wooden & synthetic badminton courts with anti-glare LED illumination, high-grip sports flooring, and spectator seating galleries.",
    feat_sports_track_title: "Synthetic Athletic Track & Field",
    feat_sports_track_desc: "International-standard synthetic athletic track for sprints, long distance, hurdle training, long jump pits, and state-level athletic meets.",
    feat_sports_football_title: "Football Stadium Ground",
    feat_sports_football_desc: "Spacious lush-green natural grass football stadium equipped with floodlights for night matches, regulation goalposts, and team dugouts.",
    feat_sports_volleyball_title: "Volleyball Courts",
    feat_sports_volleyball_desc: "Multiple floodlit outdoor sand and synthetic volleyball courts hosting inter-departmental leagues, VTU tournaments, and practice sessions.",
    feat_sports_kabaddi_title: "Kabaddi Synthetic Mat Arena",
    feat_sports_kabaddi_desc: "Indoor/outdoor pro-style synthetic Kabaddi mats for intense physical endurance training, tactical raiding drills, and state championships.",
    feat_sports_gym_title: "Indoor Games & Multi-Gymnasium",
    feat_sports_gym_desc: "Air-conditioned indoor games arena for Table Tennis, Chess, Carrom, Squash, alongside a modern, fully-equipped multi-station fitness gymnasium.",

    // Events Modal Keys
    feat_evt_nudisiri_title: "Alva's Nudisiri — National Kannada Cultural & Literary Sammelana",
    feat_evt_nudisiri_desc: "Prestigious annual national conference celebrating Kannada literature, language, poetry sessions, book exhibitions, and traditional folk heritage.",
    feat_evt_virasat_title: "Alva's Virasat & Cultural Extravaganza",
    feat_evt_virasat_desc: "Renowned national cultural fest showcasing classical music, dance recitals, folk performances, and international cultural exchange.",
    feat_evt_pragati_title: "Alva's Pragati — Mega Placement Drive",
    feat_evt_pragati_desc: "One of India's largest annual campus job fairs hosting 250+ top companies and thousands of career opportunities for graduates.",
    feat_evt_tech_title: "National Technical Symposium & Hackathons",
    feat_evt_tech_desc: "Annual inter-college engineering fest featuring 24-hour hackathons, paper presentations, robotics challenges, and AI exhibitions.",
    feat_evt_sports_title: "Annual Sports Meet & Tournaments",
    feat_evt_sports_desc: "State-level athletic championships, floodlight cricket, football, basketball, and kabaddi inter-departmental tournaments.",

    // Research
    res_title: "Student & Faculty Research Publications",
    res_subtitle: "Explore published research papers, journal articles, and conference proceedings from AIET students and faculty.",
    res_search_placeholder: "Search by topic, author, journal, or year (e.g. AI, MANET, Springer)...",
    res_authors: "Authors:",
    res_journal: "Journal/Publisher:",
    res_view_pub: "View Publication",
    res_load_more: "Load More Publications",
    res_showing: "Showing",
    res_of: "of",
    res_pubs: "publications",

    // Vision & Mission
    vm_title: "AIET Vision & Mission Statement",
    vm_subtitle: "Guiding principles driving institutional excellence.",
    vm_vision_title: "Vision of AIET",
    vm_vision_quote: "\"Transformative education by pursuing excellence in Engineering and Management through enhancing skills to meet the evolving needs of the community.\"",
    vm_vision_desc: "Our vision defines our long-term aspirations. At AIET, we aim to deliver transformative education that is adaptable, inclusive, and future-ready. We believe in empowering students not just to meet today's challenges, but to shape tomorrow.",
    vm_mission_title: "Mission of AIET",
    vm_mission_points: [
      "To impart quality technical education to the student community by inculcating knowledge, creativity, and ethics.",
      "To adopt best engineering practices through transformative education.",
      "To develop knowledgeable individuals for dynamic industrial scenarios.",
      "To inculcate research, entrepreneurial skills, and human values to meet societal needs."
    ],
    vm_mission_desc: "Our mission articulates the path to achieving our vision. Through quality-driven technical education and ethical development, we build not just professionals, but responsible citizens.",

    // Footer
    foot_title: "Alva's Institute Of Engineering & Technology",
    foot_subtitle: "(An Autonomous Institute)",
    foot_address: "Shobhavana Campus, Mijar, Moodbidri, Dakshina Kannada, Karnataka - 574225",

    // Virtual Tour
    vt_title: "Interactive Virtual Tour",
    vt_subtitle: "Click and drag inside viewport to explore campus in 360°",
    vt_loc: "Locations",
    vt_loc_gate: "Main Campus Entrance Gate",
    vt_loc_lib: "College Library Hall",

    // Admission
    adm_portal: "Admissions Portal",
    adm_sub_desc: "Secure your branch seat allocation or request an administrative meeting slot.",
    adm_req: "AIET Admission Requirements",
    adm_req_succ: "Seat Requested Successfully!",
    adm_phys: "Physical Campus Appointments",
    adm_phys_succ: "Physical Slot Registered!",
    adm_rem: "Remote Video Counseling",
    adm_rem_succ: "Virtual Counseling Set!",
    adm_tab_1: "1. Online Seat Booking",
    adm_tab_2: "2. Offline Campus Counseling",
    adm_tab_3: "3. Online Counseling (Remote)",
    adm_elig_title: "Academic Eligibility",
    adm_elig_desc: "Minimum of 45% aggregate marks in 10+2 / PUC with Physics & Mathematics as mandatory subjects.",
    adm_score_title: "Entrance Scorecards",
    adm_score_desc: "Valid metrics entry from KCET, COMEDK, or JEE Main options.",
    adm_mgt_title: "Management Quota",
    adm_mgt_desc: "Direct admission available for students meeting the minimum academic criteria.",
    adm_snq_title: "SNQ Quota",
    adm_snq_desc: "Supernumerary Quota seats for meritorious students from economically weaker sections.",
    adm_view_syl: "View Syllabus",
    adm_form_name: "Applicant Full Name",
    adm_form_email: "Email Address",
    adm_form_phone: "Contact Number",
    adm_form_branch: "Desired Program / Branch",
    adm_btn_confirm: "Confirm Online Seat Booking",
    adm_form_desk: "Select Desk Authority",
    adm_form_date: "Appointment Date",
    adm_btn_token: "Generate Entry Token",
    adm_form_email_link: "Email Address (For Invite Link)",
    adm_form_target: "Target Branch",
    adm_form_pref_date: "Preferred Consultation Date",
    adm_btn_remote: "Request Remote Consultation",
    adm_applicant_name: "Applicant Name:",
    adm_selected_branch: "Selected Branch:",
    adm_status_label: "Status:",
    adm_provisionally_saved: "Provisionally Saved",
    adm_desk_alert: "Desk Alert:",
    adm_live_queue: "Live Waiting Queue:",
    adm_virtual_route: "Virtual Desk Route:",
    adm_meet_room: "Join Live Google Meet Room",
    adm_principal_desk: "Principal's Desk",
    adm_admin_officer_desk: "Administrative Officer (Mr. Nikhil Alva)",
    adm_admin_officer_title: "Administrative Officer",
    adm_admin_officer_name: "(Mr. Nikhil Alva)",
    adm_admission_officer_desk: "Admission Officer (Mr. Tilak)",
    adm_admission_officer_title: "Admission Officer",
    adm_admission_officer_name: "(Mr. Tilak)",
    adm_opt_ug_group: "Undergraduate (UG) - B.E.",
    adm_opt_pg_group: "Postgraduate (PG)",

    // PG Admission Specific
    pg_adm_portal: "PG Admissions Portal",
    pg_adm_subtitle: "Secure your MBA seat allocation or request an administrative meeting slot.",
    pg_adm_elig_title: "Eligibility",
    pg_adm_elig_desc: "Hold a Bachelor's degree in any discipline with a minimum of 50% marks (including languages). Final year students are also encouraged to apply.",
    pg_adm_score_title: "Entrance Exams",
    pg_adm_score_desc: "Submit valid scores from one of the following entrance exams: CAT, MAT, KMAT, or PGCET. These exams assess your quantitative, analytical, and verbal reasoning skills.",
    pg_adm_sel_title: "Selection Process",
    pg_adm_sel_desc: "Shortlisted candidates will be invited for a Group Discussion (GD) and a Personal Interview (PI). These sessions allow us to assess your communication, teamwork, problem-solving, and leadership skills.",
    pg_adm_about_btn: "About MBA",
    pg_adm_about_alert: "MBA Program Details:\n- 2 Year Full Time\n- Dual Specializations\n- 100% Placement Assistance"
  },
  kn: {
    // Navbar
    nav_college_name: "ಆಳ್ವಾಸ್ ಇಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ಸಂಸ್ಥೆ",
    nav_home: "ಮುಖಪುಟ",
    nav_virtual_tour: "ವರ್ಚುವಲ್ ಟೂರ್",
    nav_placements: "ಉದ್ಯೋಗಾವಕಾಶಗಳು",
    nav_research: "ಸಂಶೋಧನೆ",
    nav_vision: "ದೃಷ್ಟಿ ಮತ್ತು ಧ್ಯೇಯ",
    nav_contact: "ಸಂಪರ್ಕಿಸಿ",
    nav_programs: "UG/PG ಕಾರ್ಯಕ್ರಮಗಳು",
    nav_apply: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    nav_back: "ಹಿಂದೆ",
    nav_ug_adm: "ಪದವಿಪೂರ್ವ (UG) ಪ್ರವೇಶಾತಿ",
    nav_pg_adm: "ಸ್ನಾತಕೋತ್ತರ (PG) ಪ್ರವೇಶಾತಿ",
    nav_admin: "ಆಡಳಿತ",
    nav_admin_portal: "ಆಡಳಿತ ಪೋರ್ಟಲ್",

    // Hero
    hero_badge: "ಆಳ್ವಾಸ್ ಇಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ಸಂಸ್ಥೆ",
    hero_autonomous: "(ಒಂದು ಸ್ವಾಯತ್ತ ಸಂಸ್ಥೆ)",
    hero_title_1: "ಮರು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತಿದೆ",
    hero_title_2: "ತಾಂತ್ರಿಕ ಮತ್ತು ನಿರ್ವಹಣಾ ಶಿಕ್ಷಣ",
    hero_title_highlight: "ಇಂಜಿನಿಯರಿಂಗ್",
    hero_title_suffix: "ಮತ್ತು ನಿರ್ವಹಣೆ",
    hero_sub_heading: "ಸೀಟ್ ಬುಕಿಂಗ್ ಮತ್ತು ಆಫ್‌ಲೈನ್/ಆನ್‌ಲೈನ್ ಕೌನ್ಸೆಲಿಂಗ್ ಬುಕಿಂಗ್",
    hero_subtitle: "ತಲ್ಲೀನಗೊಳಿಸುವ 360° ವರ್ಚುವಲ್ ಟೂರ್‌ಗಳೊಂದಿಗೆ ಪ್ರತಿ ಬ್ಲಾಕ್ ಅನ್ನು ಅನ್ವೇಷಿಸಿ, ವಿಭಾಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ, ಉದ್ಯೋಗಗಳು, ಅಧ್ಯಾಪಕರ ಮಾಹಿತಿ ಮತ್ತು ಪ್ರವೇಶ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ—ಎಲ್ಲವೂ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.",
    hero_btn_primary: "ಕ್ಯಾಂಪಸ್ ಅನ್ವೇಷಿಸಿ →",
    hero_btn_secondary: "ಡೆಮೊ ವೀಕ್ಷಿಸಿ",

    // Stats
    stats_title: "ಮೈಲಿಗಲ್ಲುಗಳು",
    stats_subtitle: "ಸಾಂಸ್ಥಿಕ ಶ್ರೇಷ್ಠತೆ ಮತ್ತು ವೃತ್ತಿಜೀವನದ ಫಲಿತಾಂಶಗಳನ್ನು ಪ್ರತಿನಿಧಿಸುವ ಪರಿಶೀಲಿಸಬಹುದಾದ ಮೈಲಿಗಲ್ಲುಗಳು.",
    stats_rank_label: "ಭಾರತದಲ್ಲಿ ಟೈಮ್ಸ್ ಇಂಜಿನಿಯರಿಂಗ್ ಶ್ರೇಣಿ",
    stats_rank_desc: "ಕರ್ನಾಟಕದ 18ನೇ ಅತ್ಯುತ್ತಮ ಇಂಜಿನಿಯರಿಂಗ್ ಸಂಸ್ಥೆ",
    stats_outlook_label: "ಔಟ್‌ಲುಕ್-ಐಸಿಎಆರ್‌ ಶ್ರೇಣಿ",
    stats_outlook_desc: "ಭಾರತದ ಪ್ರಮುಖ ಖಾಸಗಿ ಇಂಜಿನಿಯರಿಂಗ್ ಸಂಸ್ಥೆಗಳಲ್ಲಿ 53ನೇ ಶ್ರೇಣಿ",
    stats_grade_label: "NAAC ಮಾನ್ಯತೆ ಮೆಟ್ರಿಕ್",
    stats_grade_desc: "NBA ಪ್ರಮಾಣೀಕೃತ ಕೋರ್ ಟೆಕ್ ಕಾರ್ಯಕ್ರಮಗಳು (CSE ಮತ್ತು ECE)",
    stats_shortlist_label: "ಆಳ್ವಾಸ್ ಪ್ರಗತಿಯಲ್ಲಿ ಆಯ್ಕೆಯಾಗಿದ್ದಾರೆ",
    stats_shortlist_desc: "ಕರಾವಳಿ ಕರ್ನಾಟಕದ ಅತಿದೊಡ್ಡ ಮೆಗಾ ಪ್ಲೇಸ್‌ಮೆಂಟ್ ಡ್ರೈವ್ ಮೂಲಕ",
    stats_partners_label: "ಕಾರ್ಪೊರೇಟ್ ಪಾಲುದಾರರು",
    stats_partners_desc: "ಮಿಜಾರ್ ಕ್ಯಾಂಪಸ್‌ಗೆ ಭೇಟಿ ನೀಡುವ ಸಕ್ರಿಯ ನೇಮಕಾತಿದಾರರು",
    stats_news_btn: "ಆಳ್ವಾಸ್ ಸುದ್ದಿ ಕರಪತ್ರ",

    // Placements
    place_title: "ಉದ್ಯೋಗಾವಕಾಶ ದಾಖಲೆಗಳು",
    place_subtitle: "ನಮ್ಮ ಮೀಸಲಾದ ತರಬೇತಿ ಮತ್ತು ಉದ್ಯೋಗ ಕೋಶದಿಂದ ಪರಿಶೀಲಿಸಬಹುದಾದ ವೃತ್ತಿ ಅಂಕಿಅಂಶಗಳು.",
    place_high_ctc: "ಅತ್ಯಧಿಕ CTC ಪ್ಯಾಕ್",
    place_high_desc: "ವೀಸಾದಲ್ಲಿ (Visa) ಪಡೆಯಲಾಗಿದೆ",
    place_sec_ctc: "ಎರಡನೇ ಅತ್ಯಧಿಕ",
    place_sec_desc: "ಜಸ್‌ಪೇಯಲ್ಲಿ ಪಡೆಯಲಾಗಿದೆ",
    place_avg_ctc: "ಸರಾಸರಿ ಮೆಟ್ರಿಕ್",
    place_avg_desc: "ಸಾಂಸ್ಥಿಕ ಆಧಾರ",
    place_corp: "ಕಾರ್ಪೊರೇಟ್ ಪಾಲುದಾರರು",
    place_corp_desc: "ಸಕ್ರಿಯ ನೇಮಕಾತಿ",
    place_prom_title: "ಪ್ರಮುಖ ನೇಮಕಾತಿ ಪಾಲುದಾರರು",
    place_prom_subtitle: "ನಮ್ಮ ಮಿಜಾರ್ ಕ್ಯಾಂಪಸ್‌ನಿಂದ ನೇರವಾಗಿ ತಾಂತ್ರಿಕ ಪ್ರತಿಭೆಗಳನ್ನು ಸಕ್ರಿಯವಾಗಿ ಆಯ್ಕೆ ಮಾಡುವ ಸಂಸ್ಥೆಗಳು.",
    place_recent_milestones: "ಇತ್ತೀಚಿನ ಉದ್ಯೋಗಾವಕಾಶ ಮೈಲಿಗಲ್ಲುಗಳು",
    place_why_aiet: "ತರಬೇತಿ ಮತ್ತು ಉದ್ಯೋಗಾವಕಾಶಕ್ಕಾಗಿ ಆಳ್ವಾಸ್ ಸಂಸ್ಥೆ ಏಕೆ ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆ?",
    place_view_posters: "ಇತ್ತೀಚಿನ ಉದ್ಯೋಗಾವಕಾಶ ಮೈಲಿಗಲ್ಲುಗಳನ್ನು ವೀಕ್ಷಿಸಿ (27 ಪೋಸ್ಟರ್‌ಗಳು)",
    place_click_poster: "ಪೂರ್ಣ ವಿವರಗಳಲ್ಲಿ ವೀಕ್ಷಿಸಲು ಯಾವುದೇ ಪೋಸ್ಟರ್ ಮೇಲೆಯೂ ಕ್ಲಿಕ್ ಮಾಡಿ",
    place_view_all_partners: "ಎಲ್ಲಾ ನೇಮಕಾತಿ ಪಾಲುದಾರರನ್ನು ವೀಕ್ಷಿಸಿ (156+ ಸಂಸ್ಥೆಗಳು)",
    place_modal_subtitle: "ಆಳ್ವಾಸ್ ಕ್ಯಾಂಪಸ್ ಡ್ರೈವ್‌ಗಳಿಂದ ನೇಮಕಾತಿ ಮಾಡಿಕೊಳ್ಳುವ ಎಲ್ಲಾ 156+ ಕಾರ್ಪೊರೇಟ್ ನೇಮಕಾತಿದಾರರನ್ನು ಅನ್ವೇಷಿಸಿ",
    place_recent_subtitle: "ವಿದ್ಯಾರ್ಥಿ ಉದ್ಯೋಗಾವಕಾಶ ಕೊಡುಗೆಗಳು, ಕಾರ್ಪೊರೇಟ್ ನೇಮಕಾತಿ ಪೋಸ್ಟರ್‌ಗಳು ಮತ್ತು ಕ್ಯಾಂಪಸ್ ನೇಮಕಾತಿ ವಿವರಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    place_ecosystem_subtitle: "ಆಳ್ವಾಸ್ ಸಂಸ್ಥೆಯ ಸಮರ್ಪಿತ ಉದ್ಯೋಗಾವಕಾಶ ವ್ಯವಸ್ಥೆಯು ಪ್ರತಿಯೊಬ್ಬ ವಿದ್ಯಾರ್ಥಿಯ ವೃತ್ತಿಜೀವನದ ಅವಕಾಶಗಳನ್ನು ಹೆಚ್ಚಿಸುವತ್ತ ಗಮನಹರಿಸುತ್ತದೆ.",
    place_feat_1: "2ನೇ ವರ್ಷದಿಂದ ಉನ್ನತ ಮಟ್ಟದ ಪೂರ್ವ-ಉದ್ಯೋಗಾವಕಾಶ ತಾಂತ್ರಿಕ ತರಬೇತಿ ಕಾರ್ಯಕ್ರಮಗಳು.",
    place_feat_2: "ತಾಂತ್ರಿಕ ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಕಾರ್ಯಾಗಾರಗಳು.",
    place_feat_3: "1ನೇ ಸೆಮಿಸ್ಟರ್‌ನಿಂದಲೇ ಸಾಫ್ಟ್ ಸ್ಕಿಲ್ಸ್ ಮತ್ತು ವ್ಯಕ್ತಿತ್ವ ವಿಕಸನ ತರಗತಿಗಳು.",
    place_feat_4: "6LPA ನಿಂದ 36LPA ವರೆಗಿನ PPO ಕೊಡುಗೆಗಳೊಂದಿಗೆ ಇಂಟರ್ನ್‌ಶಿಪ್ ಅವಕಾಶಗಳು.",
    place_feat_5: "ಕ್ಯಾಂಪಸ್ ಮತ್ತು ಆಫ್-ಕ್ಯಾಂಪಸ್ ನೇಮಕಾತಿ ಅಭಿಯಾನಗಳು.",
    place_feat_6: "ಪೂಲ್ ಕ್ಯಾಂಪಸ್ ಮತ್ತು ಬೃಹತ್ ನೇಮಕಾತಿ ಕಾರ್ಯಕ್ರಮಗಳು.",
    place_feat_7: "ರೆಸ್ಯೂಮ್ ತಯಾರಿ ಮತ್ತು ಲಿಂಕ್ಡ್‌ಇನ್ ಪ್ರೊಫೈಲ್ ಸುಧಾರಣೆ.",
    place_feat_8: "ಉದ್ಯಮ ತಜ್ಞರಿಂದ ಮಾಕ್ ಇಂಟರ್ವ್ಯೂ, ಆಪ್ಟಿಟ್ಯೂಡ್ ತರಬೇತಿ ಮತ್ತು HR ಸಿದ್ಧತೆ.",
    place_feat_9: "ಇನ್-ಹೌಸ್ ಟೆಕ್ನಾಲಜಿ ಸೆಂಟರ್‌ನ ತಜ್ಞರು ಸೇರಿದಂತೆ ಕಂಪನಿ ಪ್ರೊಫೆಷನಲ್‌ಗಳಿಂದ ಮಾರ್ಗದರ್ಶನ.",

    // Faculty
    fac_title: "ತಜ್ಞ ಬೋಧಕ ವರ್ಗದ ಪ್ರೊಫೈಲ್‌ಗಳು",
    fac_subtitle: "ಸಂಶೋಧನೆ ಮತ್ತು ಎಂಜಿನಿಯರಿಂಗ್ ಆವಿಷ್ಕಾರವನ್ನು ಮುನ್ನಡೆಸುತ್ತಿರುವ ಶೈಕ್ಷಣಿಕ ಮಾರ್ಗದರ್ಶಕರಿಂದ ಕಲಿಯಿರಿ.",
    fac_dept_all: "ಎಲ್ಲಾ ವಿಭಾಗಗಳು",
    fac_dept_admin: "ಆಡಳಿತ",
    fac_dept_cse: "ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ ಮತ್ತು ಇಂಜಿನಿಯರಿಂಗ್",
    fac_dept_ise: "ಮಾಹಿತಿ ವಿಜ್ಞಾನ ಮತ್ತು ಇಂಜಿನಿಯರಿಂಗ್",
    fac_dept_ece: "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಸಂವಹನ ಇಂಜಿನಿಯರಿಂಗ್",
    fac_dept_civil: "ಸಿವಿಲ್ ಇಂಜಿನಿಯರಿಂಗ್",
    fac_dept_me: "ಮೆಕ್ಯಾನಿಕಲ್ ಇಂಜಿನಿಯರಿಂಗ್",
    fac_dept_aiml: "AI ಮತ್ತು ಮೆಷಿನ್ ಲರ್ನಿಂಗ್",
    fac_dept_aids: "AI ಮತ್ತು ಡೇಟಾ ಸೈನ್ಸ್",
    fac_dept_csd: "ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ ಮತ್ತು ವಿನ್ಯಾಸ",
    fac_dept_iot: "IoT ಮತ್ತು ಸೈಬರ್ ಭದ್ರತೆ",
    fac_dept_mba: "ಮಾಸ್ಟರ್ ಆಫ್ ಬ್ಯುಸಿನೆಸ್ ಅಡ್ಮಿನಿಸ್ಟ್ರೇಷನ್ (MBA)",
    fac_dept_ug: "ಪದವಿಪೂರ್ವ (UG)",
    fac_dept_pg: "ಸ್ನಾತಕೋತ್ತರ (PG)",
    fac_role_prin: "ಪ್ರಾಂಶುಪಾಲರು ಮತ್ತು ಪ್ರಾಧ್ಯಾಪಕರು",
    fac_role_prof_hod: "ಪ್ರಾಧ್ಯಾಪಕರು ಮತ್ತು HOD",
    fac_role_assoc: "ಸಹ ಪ್ರಾಧ್ಯಾಪಕರು",
    fac_role_assist: "ಸಹಾಯಕ ಪ್ರಾಧ್ಯಾಪಕರು",
    fac_role_snr_assist: "ಹಿರಿಯ ಸಹಾಯಕ ಪ್ರಾಧ್ಯಾಪಕರು",
    fac_role_adm_off: "ಪ್ರವೇಶಾಧಿಕಾರಿ",

    // Contact
    contact_title: "ಆಡಳಿತ ಕಚೇರಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ",
    contact_subtitle: "ಅಧಿಕೃತ ಆಳ್ವಾಸ್ ಪ್ರವೇಶಾತಿ ಡೆಸ್ಕ್ ಅನ್ನು ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ.",
    contact_loc_title: "ಕ್ಯಾಂಪಸ್ ಸ್ಥಳ",
    contact_loc_desc: "ಶೋಭಾವನ ಕ್ಯಾಂಪಸ್, ಮಿಜಾರ್, ಮೂಡುಬಿದಿರೆ, ದಕ್ಷಿಣ ಕನ್ನಡ, ಕರ್ನಾಟಕ - 574225",
    contact_loc_link: "ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ →",
    contact_hotline_title: "ಪ್ರವೇಶಾತಿ ಕಚೇರಿ ಸಹಾಯವಾಣಿಗಳು",
    contact_call_now: "[ಈಗ ಕರೆ ಮಾಡಿ]",
    contact_mail_title: "ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಡೆಸ್ಕ್",
    contact_mail_link: "ಮೇಲ್ ಇನ್‌ಬಾಕ್ಸ್ ತೆರೆಯಿರಿ →",
    contact_form_title: "ತಕ್ಷಣದ ವಿಚಾರಣೆಯನ್ನು ಕಳುಹಿಸಿ",
    contact_form_name: "ನಿಮ್ಮ ಹೆಸರು",
    contact_form_email: "ನಿಮ್ಮ ಇಮೇಲ್",
    contact_form_msg: "ಕೋರ್ಸ್‌ಗಳು, ಶುಲ್ಕಗಳು ಅಥವಾ ಹಾಸ್ಟೆಲ್ ಲಭ್ಯತೆಯ ಕುರಿತು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    contact_form_btn: "ಪ್ರಶ್ನೆ ಕಳುಹಿಸಿ",
    contact_status_sending: "ವಿಚಾರಣೆ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    contact_status_success: "🎉 ವಿಚಾರಣೆ ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ!",
    contact_status_fail: "❌ ಕಳುಹಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ:",
    contact_status_error: "❌ ಬ್ಯಾಕೆಂಡ್‌ಗೆ ಸಂಪರ್ಕಿಸುವಾಗ ನೆಟ್‌ವರ್ಕ್ ದೋಷ.",

    // Features
    feat_title: "ಕ್ಯಾಂಪಸ್ ಸೌಕರ್ಯಗಳು ಮತ್ತು ಸೌಲಭ್ಯಗಳು",
    feat_subtitle: "ವಿದ್ಯಾರ್ಥಿಗಳ ಬೆಳವಣಿಗೆಗೆ ಶ್ರೇಷ್ಠವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಕ್ಯಾಂಪಸ್ ಸೌಲಭ್ಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    btn_preview: "ಪೂರ್ವವೀಕ್ಷಣೆ",
    feat_hostel_title: "ಕಾಲೇಜು ಹಾಸ್ಟೆಲ್",
    feat_hostel_desc: "24/7 ಭದ್ರತೆ ಮತ್ತು ಸ್ವಚ್ಛ ವಾತಾವರಣವಿರುವ ಪ್ರತ್ಯೇಕ ಪುರುಷರ ಮತ್ತು ಮಹಿಳೆಯರ ಹಾಸ್ಟೆಲ್‌ಗಳು.",
    feat_food_title: "ಹಾಸ್ಟೆಲ್ ಮೆಸ್",
    feat_food_desc: "ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಪ್ರತಿದಿನ ಸ್ವಚ್ಛ ಹಾಗೂ ರುಚಿಕರ ಸಸ್ಯಾಹಾರಿ ಮತ್ತು ಮಾಂಸಾಹಾರಿ ಊಟ.",
    feat_sports_title: "ಕ್ರೀಡಾ ಮೈದಾನಗಳು",
    feat_sports_desc: "ಕ್ರೀಡೆ ಮತ್ತು ಅಥ್ಲೆಟಿಕ್ಸ್ ತರಬೇತಿಗಾಗಿ ವಿಶಾಲವಾದ ಆಟದ ಮೈದಾನಗಳು.",
    feat_badm_title: "ಬ್ಯಾಡ್ಮಿಂಟನ್ ಕೋರ್ಟ್‌ಗಳು",
    feat_badm_desc: "ತರಬೇತಿ ಮತ್ತು ಆಟಗಳಿಗಾಗಿ ವೃತ್ತಿಪರ ಒಳಾಂಗಣ ಬ್ಯಾಡ್ಮಿಂಟನ್ ಕೋರ್ಟ್‌ಗಳು.",
    feat_swim_title: "ಈಜುಕೊಳ",
    feat_swim_desc: "ತರಬೇತಿ ಮತ್ತು ಈಜು ಅಭ್ಯಾಸಕ್ಕಾಗಿ ಸ್ವಚ್ಛ ಹಾಗೂ ಸುಂದರ ಈಜುಕೊಳ.",
    feat_clubs_title: "40+ ಸಕ್ರಿಯ ಕ್ಲಬ್‌ಗಳು",
    feat_clubs_desc: "ತಾಂತ್ರಿಕ, ಸಾಂಸ್ಕೃತಿಕ ಮತ್ತು ಸಾಮಾಜಿಕ ಚಟುವಟಿಕೆಗಳಿಗಾಗಿ 40 ಕ್ಕೂ ಹೆಚ್ಚು ಕ್ಲಬ್‌ಗಳು.",
    feat_ncc_title: "ಎನ್‌ಸಿಸಿ ಕಾರ್ಪ್ಸ್",
    feat_ncc_desc: "ಶಿಸ್ತು ಮತ್ತು ನಾಯಕತ್ವ ಬೆಳೆಸುವ ಎನ್‌ಸಿಸಿ (NCC) ಘಟಕ.",
    feat_gym_title: "ಫಿಟ್ನೆಸ್ ಜಿಮ್ನಾಷಿಯಂ",
    feat_gym_desc: "ಆಧುನಿಕ ವ್ಯಾಯಾಮ ಉಪಕರಣಗಳು ಮತ್ತು ತರಬೇತುದಾರರನ್ನು ಹೊಂದಿರುವ ಜಿಮ್.",
    feat_shoba_title: "ಶೋಭಾವನ ಕ್ಯಾಂಪಸ್",
    feat_shoba_desc: "ಕಲಿಕೆಗೆ ಪ್ರಶಾಂತ ವಾತಾವರಣ ನೀಡುವ ಹಚ್ಚ ಹಸಿರಿನ ಪರಿಸರ ಸ್ನೇಹಿ ಕ್ಯಾಂಪಸ್.",
    feat_medical_title: "ವೈದ್ಯಕೀಯ ಸೌಲಭ್ಯ",
    feat_medical_desc: "ವೈದ್ಯಕೀಯ ಸಿಬ್ಬಂದಿ ಮತ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್ ಸೌಲಭ್ಯದೊಂದಿಗೆ 24/7 ಆರೋಗ್ಯ ಕೇಂದ್ರ.",
    feat_bus_title: "ಕಾಲೇಜು ಸಾರಿಗೆ",
    feat_bus_desc: "ಮುಖ್ಯ ಮಾರ್ಗಗಳನ್ನು ಸಂಪರ್ಕಿಸುವ ಸುರಕ್ಷಿತ ಕಾಲೇಜು ಬಸ್ ಸಾರಿಗೆ.",
    feat_campus_main_title: "ಮುಖ್ಯ ಕ್ಯಾಂಪಸ್ ಕಟ್ಟಡಗಳು",
    feat_campus_main_desc: "ಹಸಿರಿನಿಂದ ಆವೃತವಾದ ಮುಖ್ಯ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ಆಡಳಿತ ಕಟ್ಟಡಗಳು.",
    feat_hostel_room_title: "ಹಾಸ್ಟೆಲ್ ಕೊಠಡಿಗಳು",
    feat_hostel_room_desc: "ಸ್ಟಡಿ ಟೇಬಲ್, ವಾರ್ಡ್‌ರೋಬ್ ಮತ್ತು ವೈ-ಫೈ ಹೊಂದಿರುವ ಕೊಠಡಿಗಳು.",
    feat_park_title: "ಹಸಿರು ಉದ್ಯಾನವನಗಳು",
    feat_park_desc: "ವಿಶ್ರಾಂತಿ ಮತ್ತು ಓದಿಗೆ ಸುಂದರವಾದ ಹಸಿರು ಉದ್ಯಾನವನಗಳು.",
    feat_stationary_title: "ಸ್ಟೇಷನರಿ ಅಂಗಡಿ",
    feat_stationary_desc: "ವಿದ್ಯಾರ್ಥಿಗಳ ದೈನಂದಿನ ಅಗತ್ಯಗಳಿಗಾಗಿ ಕ್ಯಾಂಪಸ್ ಸ್ಟೇಷನರಿ ಅಂಗಡಿ.",
    feat_foodcourt_title: "ಫುಡ್ ಕೋರ್ಟ್",
    feat_foodcourt_desc: "ರುಚಿಕರ ಊಟ ಮತ್ತು ತಿಂಡಿಗಳನ್ನು ನೀಡುವ ಸ್ವಚ್ಛ ಫುಡ್ ಕೋರ್ಟ್.",
    feat_kudla_title: "ಕುಡ್ಲ ಮಿಲಿಟರಿ ಹೋಟೆಲ್",
    feat_kudla_desc: "ತಾಜಾ ಮತ್ತು ರುಚಿಕರವಾದ ಸ್ಥಳೀಯ ಮಾಂಸಾಹಾರಿ ಊಟ.",
    feat_kitchen_title: "ಕಿಚನ್ ಎಕ್ಸ್‌ಪ್ರೆಸ್",
    feat_kitchen_desc: "ತ್ವರಿತ ಆಹಾರ, ತಿಂಡಿಗಳು ಮತ್ತು ಪಾನೀಯಗಳು.",
    feat_ac_class_title: "ಹವಾನಿಯಂತ್ರಿತ ತರಗತಿ ಕೊಠಡಿಗಳು",
    feat_ac_class_desc: "ಡಿಜಿಟಲ್ ಬೋಧನಾ ಸಾಧನಗಳನ್ನು ಹೊಂದಿರುವ ಎಸಿ ತರಗತಿ ಕೊಠಡಿಗಳು.",
    feat_lift_title: "ಕ್ಯಾಂಪಸ್ ಎಲಿವೇಟರ್‌ಗಳು",
    feat_lift_desc: "ಎಲ್ಲಾ ಕಟ್ಟಡಗಳಲ್ಲಿ ಸುಲಭ ಸಂಚಾರಕ್ಕಾಗಿ ಹೆಚ್ಚಿನ ವೇಗದ ಲಿಫ್ಟ್‌ಗಳು.",
    feat_campus_sel_title: "ಕ್ಯಾಂಪಸ್ ಆಯ್ಕೆ",
    feat_campus_sel_desc: "ಉನ್ನತ ಕಂಪನಿಗಳೊಂದಿಗೆ ಉದ್ಯೋಗ ಅವಕಾಶಗಳನ್ನು ಒದಗಿಸುವ ಪ್ಲೇಸ್‌ಮೆಂಟ್ ಸೆಲ್.",
    feat_adv_lab_title: "ಸುಧಾರಿತ ಪ್ರಯೋಗಾಲಯಗಳು",
    feat_adv_lab_desc: "ಆಧುನಿಕ ಸಾಫ್ಟ್‌ವೇರ್ ಮತ್ತು ಉಪಕರಣಗಳನ್ನು ಹೊಂದಿರುವ ಲ್ಯಾಬ್‌ಗಳು.",
    feat_lib_title: "ಕಾಲೇಜು ಗ್ರಂಥಾಲಯ",
    feat_lib_desc: "ಪುಸ್ತಕಗಳು ಮತ್ತು ಡಿಜಿಟಲ್ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಹೊಂದಿರುವ ಪ್ರಶಾಂತ ಕಾಲೇಜು ಗ್ರಂಥಾಲಯ.",
    feat_atm_title: "ಕ್ಯಾಂಪಸ್ ಎಟಿಎಂ",
    feat_atm_desc: "ಕ್ಯಾಂಪಸ್‌ನಲ್ಲಿ 24/7 ಎಟಿಎಂ ಸೌಲಭ್ಯ.",
    feat_trainer_title: "ನಮ್ಮ ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳು ಮತ್ತು ಕೈಗಾರಿಕಾ ಇನ್-ಹೌಸ್",
    feat_trainer_desc: "ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಕೆಲಸಕ್ಕೆ ಸಿದ್ಧಗೊಳಿಸಲು ಅನುಭವಿ ತಜ್ಞರಿಂದ ತರಬೇತಿ.",
    feat_startups_title: "ನಮ್ಮ ನವೋದ್ಯಮಗಳು",
    feat_startups_desc: "ವಿದ್ಯಾರ್ಥಿ ಮತ್ತು ಹಳೆಯ ವಿದ್ಯಾರ್ಥಿಗಳ ನವೋದ್ಯಮಗಳು ಹಾಗೂ ತಂತ್ರಜ್ಞಾನ ಆವಿಷ್ಕಾರಗಳು.",
    feat_industrial_title: "ಕೈಗಾರಿಕಾ ಇನ್-ಹೌಸ್",
    feat_industrial_desc: "ಕ್ಯಾಂಪಸ್‌ನಲ್ಲಿ ಉದ್ಯಮ-ಸಹಭಾಗಿತ್ವದ ಕೌಶಲ್ಯ ಹಬ್‌ಗಳು ಮತ್ತು ತರಬೇತಿ ಕೇಂದ್ರಗಳು.",
    feat_events_title: "ಕಾಲೇಜು ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಉತ್ಸವಗಳು",
    feat_events_desc: "ವಾರ್ಷಿಕ ಸಾಂಸ್ಕೃತಿಕ ಉತ್ಸವಗಳು, ತಾಂತ್ರಿಕ ಪ್ರದರ್ಶನಗಳು, ಹ್ಯಾಕಥಾನ್‌ಗಳು ಮತ್ತು ಕ್ರೀಡಾ ಕೂಟಗಳು.",
    feat_co_infosys_title: "ಇನ್ಫೋಸಿಸ್ (Infosys)",
    feat_co_infosys_desc: "ಮುಂದಿನ ಪೀಳಿಗೆಯ ಡಿಜಿಟಲ್ ಸೇವೆಗಳು ಮತ್ತು ಸಲಹಾದಲ್ಲಿ ಜಾಗತಿಕ ನಾಯಕ.",
    feat_co_stellium_title: "ಸ್ಟೆಲಿಯಮ್ (Stellium)",
    feat_co_stellium_desc: "ಪೂರೈಕೆ ಸರಪಳಿ, ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ವ್ಯಾಪಾರ ಪರಿವರ್ತನೆಯಲ್ಲಿ ಪರಿಣತಿ ಹೊಂದಿದೆ.",
    feat_co_kakunje_title: "ಕಾಕುಂಜೆ ಸಾಫ್ಟ್‌ವೇರ್ (Kakunje Software)",
    feat_co_kakunje_desc: "ನವೀನ ಸಾಫ್ಟ್‌ವೇರ್ ಪರಿಹಾರಗಳು ಮತ್ತು ಐಟಿ ಕನ್ಸಲ್ಟಿಂಗ್ ಸೇವೆಗಳು.",
    feat_co_metasoft_title: "ಮೆಟಾಸಾಫ್ಟ್ (Metasoft)",
    feat_co_metasoft_desc: "ಉನ್ನತ ಗುಣಮಟ್ಟದ ಸಾಫ್ಟ್‌ವೇರ್ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಎಂಜಿನಿಯರಿಂಗ್ ಪರಿಹಾರಗಳನ್ನು ತಲುಪಿಸುವುದು.",
    feat_co_strae_title: "ಸ್ಟ್ರೇ ಕಾನ್ (StraeCon)",
    feat_co_strae_desc: "ಕಾರ್ಯತಂತ್ರದ ಸಲಹಾ ಮತ್ತು ಸುಧಾರಿತ ಐಟಿ ಮೂಲಸೌಕರ್ಯ ಸೇವೆಗಳು.",
    feat_co_toyota_title: "ಟೊಯೋಟಾ ಮತ್ತು ಬೋಶ್ ಕೌಶಲ್ಯಾಭಿವೃದ್ಧಿ ಲ್ಯಾಬ್‌ಗಳು",
    feat_co_toyota_desc: "ಆಟೋಮೋಟಿವ್, ರೋಬೋಟಿಕ್ಸ್ ಮತ್ತು ಸುಧಾರಿತ ಸ್ವಯಂಚಾಲಿತ ತರಬೇತಿ ಉಪಕರಣಗಳನ್ನು ಹೊಂದಿರುವ ಕೈಗಾರಿಕಾ ತರಬೇತಿ ಕೇಂದ್ರಗಳು.",
    feat_startup_modal_title: "ಇ-ಸೆಲ್ ಆಳ್ವಾಸ್ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ಕೇಂದ್ರದ ನವೋದ್ಯಮಗಳು",
    label_founder: "ಸಂಸ್ಥಾಪಕರು:",
    btn_visit_website: "ವೆಬ್‌ಸೈಟ್‌ಗೆ ಭೇಟಿ ನೀಡಿ",

    // Sports Grounds Modal Keys
    feat_sports_modal_title: "ಕ್ರೀಡಾ ಮೈದಾನಗಳು ಮತ್ತು ಅಥ್ಲೆಟಿಕ್ಸ್ ಸೌಲಭ್ಯಗಳು",
    feat_sports_pool_title: "ಈಜುಕೊಳ ಸಮುಚ್ಛಯ",
    feat_sports_pool_desc: "ಆಧುನಿಕ ನೀರು ಶೋಧನೆ ವ್ಯವಸ್ಥೆ, ವೃತ್ತಿಪರ ತರಬೇತುದಾರರು ಮತ್ತು ಈಜು ಪಥಗಳನ್ನು ಹೊಂದಿರುವ ಒಲಿಂಪಿಕ್ ಮಟ್ಟದ ಸುಸಜ್ಜಿತ ಈಜುಕೊಳ.",
    feat_sports_badm_title: "ಬ್ಯಾಡ್ಮಿಂಟನ್ ಕೋರ್ಟ್",
    feat_sports_badm_desc: "ಎಲ್‌ಇಡಿ ಬೆಳಕಿನ ವ್ಯವಸ್ಥೆ ಮತ್ತು ವೀಕ್ಷಕರ ಗ್ಯಾಲರಿಯೊಂದಿಗೆ ಹೊಂದಿಕೊಂಡ ಒಳಾಂಗಣ ಮರದ ಹಾಗೂ ಸಿಂಥೆಟಿಕ್ ಬ್ಯಾಡ್ಮಿಂಟನ್ ಕೋರ್ಟ್‌ಗಳು.",
    feat_sports_track_title: "ಸಿಂಥೆಟಿಕ್ ಅಥ್ಲೆಟಿಕ್ಸ್ ಟ್ರ್ಯಾಕ್",
    feat_sports_track_desc: "ಓಟ, ಉದ್ದ ಜಿಗಿತ ಹಾಗೂ ಕ್ರೀಡಾಕೂಟಗಳಿಗಾಗಿ ಅಂತರರಾಷ್ಟ್ರೀಯ ದರ್ಜೆಯ ಸಿಂಥೆಟಿಕ್ ಅಥ್ಲೆಟಿಕ್ಸ್ ಟ್ರ್ಯಾಕ್.",
    feat_sports_football_title: "ಫುಟ್‌ಬಾಲ್ ಕ್ರೀಡಾಂಗಣ",
    feat_sports_football_desc: "ರಾತ್ರಿ ಪಂದ್ಯಗಳಿಗಾಗಿ ಫ್ಲಡ್‌ಲೈಟ್‌ಗಳು ಮತ್ತು ನೈಸರ್ಗಿಕ ಹಸಿರು ಹುಲ್ಲಿನ ವಿಶಾಲವಾದ ಫುಟ್‌ಬಾಲ್ ಕ್ರೀಡಾಂಗಣ.",
    feat_sports_volleyball_title: "ವಾಲಿಬಾಲ್ ಕೋರ್ಟ್‌ಗಳು",
    feat_sports_volleyball_desc: "ವಿಶ್ವವಿದ್ಯಾನಿಲಯ ಮಟ್ಟದ ಪಂದ್ಯಾವಳಿಗಳು ಮತ್ತು ತರಬೇತಿಗಾಗಿ ಫ್ಲಡ್‌ಲೈಟ್ ಸೌಲಭ್ಯವಿರುವ ವಾಲಿಬಾಲ್ ಅಂಕಣಗಳು.",
    feat_sports_kabaddi_title: "ಕಬಡ್ಡಿ ಸಿಂಥೆಟಿಕ್ ಮ್ಯಾಟ್ ಅರೇನಾ",
    feat_sports_kabaddi_desc: "ತೀವ್ರ ಕಬಡ್ಡಿ ಅಭ್ಯಾಸ ಮತ್ತು ರಾಜ್ಯ ಮಟ್ಟದ ಚಾಂಪಿಯನ್‌ಷಿಪ್‌ಗಳಿಗಾಗಿ ಪ್ರೊ-ಸ್ಟೈಲ್ ಸಿಂಥೆಟಿಕ್ ಕಬಡ್ಡಿ ಮ್ಯಾಟ್‌ಗಳು.",
    feat_sports_gym_title: "ಒಳಾಂಗಣ ಆಟಗಳು ಮತ್ತು ಮಲ್ಟಿ-ಜಿಮ್",
    feat_sports_gym_desc: "ಟೇಬಲ್ ಟೆನ್ನಿಸ್, ಚೆಸ್, ಕ್ಯಾರಮ್ ಹಾಗೂ ಆಧುನಿಕ ವ್ಯಾಯಾಮ ಉಪಕರಣಗಳನ್ನು ಹೊಂದಿರುವ ಹವಾನಿಯಂತ್ರಿತ ಮಲ್ಟಿ-ಜಿಮ್.",

    // Events Modal Keys
    feat_evt_nudisiri_title: "ಆಳ್ವಾಸ್ ನುಡಿಸಿರಿ — ರಾಷ್ಟ್ರೀಯ ಕನ್ನಡ ಸಾಂಸ್ಕೃತಿಕ ಮತ್ತು ಸಾಹಿತ್ಯ ಸಮ್ಮೇಳನ",
    feat_evt_nudisiri_desc: "ಕನ್ನಡ ಸಾಹಿತ್ಯ, ಭಾಷೆ, ಕವಿಗೋಷ್ಠಿ, ಪುಸ್ತಕ ಪ್ರದರ್ಶನ ಮತ್ತು ಜಾನಪದ ಪರಂಪರೆಯನ್ನು ಸಂಭ್ರಮಿಸುವ ರಾಷ್ಟ್ರೀಯ ಸಾಹಿತ್ಯೋತ್ಸವ.",
    feat_evt_virasat_title: "ಆಳ್ವಾಸ್ ವಿರಾಸತ್ — ರಾಷ್ಟ್ರೀಯ ಸಾಂಸ್ಕೃತಿಕ ಉತ್ಸವ",
    feat_evt_virasat_desc: "ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ, ನೃತ್ಯ ಮತ್ತು ಅಂತರರಾಷ್ಟ್ರೀಯ ಸಾಂಸ್ಕೃತಿಕ ಕಲೆಗಳನ್ನು ಪ್ರದರ್ಶಿಸುವ ವಿಶ್ವಪ್ರಸಿದ್ಧ ಸಾಂಸ್ಕೃತಿಕ ಉತ್ಸವ.",
    feat_evt_pragati_title: "ಆಳ್ವಾಸ್ ಪ್ರಗತಿ — ಬೃಹತ್ ಉದ್ಯೋಗ ಮೇಳ",
    feat_evt_pragati_desc: "250ಕ್ಕೂ ಹೆಚ್ಚು ಉನ್ನತ ಕಂಪನಿಗಳು ಭಾಗವಹಿಸುವ ಭಾರತದ ಅತಿದೊಡ್ಡ ವಾರ್ಷಿಕ ಕ್ಯಾಂಪಸ್ ಉದ್ಯೋಗ ಮೇಳ.",
    feat_evt_tech_title: "ರಾಷ್ಟ್ರೀಯ ತಾಂತ್ರಿಕ ವಿಚಾರ ಸಂಕಿರಣ ಮತ್ತು ಹ್ಯಾಕಥಾನ್",
    feat_evt_tech_desc: "24-ಗಂಟೆಗಳ ಹ್ಯಾಕಥಾನ್, ಪ್ರಬಂಧ ಮಂಡನೆ, ರೋಬೋಟಿಕ್ಸ್ ಮತ್ತು AI ಪ್ರದರ್ಶನಗಳನ್ನು ಒಳಗೊಂಡ ವಾರ್ಷಿಕ ಇಂಜಿನಿಯರಿಂಗ್ ಉತ್ಸವ.",
    feat_evt_sports_title: "ವಾರ್ಷಿಕ ಕ್ರೀಡಾಕೂಟ ಮತ್ತು ಪಂದ್ಯಾವಳಿಗಳು",
    feat_evt_sports_desc: "ರಾಜ್ಯ ಮಟ್ಟದ ಅಥ್ಲೆಟಿಕ್ಸ್ ಚಾಂಪಿಯನ್‌ಷಿಪ್‌ಗಳು ಮತ್ತು ಕ್ರೀಡಾ ಪಂದ್ಯಾವಳಿಗಳು.",

    // Research
    res_title: "ವಿದ್ಯಾರ್ಥಿ ಮತ್ತು ಬೋಧಕರ ಸಂಶೋಧನಾ ಪ್ರಕಟಣೆಗಳು",
    res_subtitle: "ಆಳ್ವಾಸ್ ಸಂಸ್ಥೆಯ ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ಬೋಧಕರ ಪ್ರಕಟಿತ ಸಂಶೋಧನಾ ಪ್ರಬಂಧಗಳು ಮತ್ತು ಜರ್ನಲ್ ಲೇಖನಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    res_search_placeholder: "ವಿಷಯ, ಲೇಖಕರು, ಜರ್ನಲ್ ಅಥವಾ ವರ್ಷದ ಮೂಲಕ ಹುಡುಕಿ (ಉದಾ: AI, MANET)...",
    res_authors: "ಲೇಖಕರು:",
    res_journal: "ಜರ್ನಲ್/ಪ್ರಕಾಶಕರು:",
    res_view_pub: "ಪ್ರಕಟಣೆಯನ್ನು ವೀಕ್ಷಿಸಿ",
    res_load_more: "ಇನ್ನಷ್ಟು ಪ್ರಕಟಣೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    res_showing: "ತೋರಿಸಲಾಗುತ್ತಿದೆ",
    res_of: "ರ ಪೈಕಿ",
    res_pubs: "ಸಂಶೋಧನಾ ಪ್ರಕಟಣೆಗಳು",

    // Vision & Mission
    vm_title: "AIET ದೃಷ್ಟಿ ಮತ್ತು ಧ್ಯೇಯ ಹೇಳಿಕೆ",
    vm_subtitle: "ಸಾಂಸ್ಥಿಕ ಶ್ರೇಷ್ಠತೆಯನ್ನು ಮುನ್ನಡೆಸುವ ಮಾರ್ಗದರ್ಶಿ ತತ್ವಗಳು.",
    vm_vision_title: "AIET ಯ ದೃಷ್ಟಿ",
    vm_vision_quote: "\"ಸಮುದಾಯದ ವಿಕಸನಗೊಳ್ಳುತ್ತಿರುವ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸಲು ಕೌಶಲ್ಯಗಳನ್ನು ಹೆಚ್ಚಿಸುವ ಮೂಲಕ ಎಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್‌ನಲ್ಲಿ ಶ್ರೇಷ್ಠತೆಯನ್ನು ಅನುಸರಿಸುವ ಮೂಲಕ ಪರಿವರ್ತಕ ಶಿಕ್ಷಣ.\"",
    vm_vision_desc: "ನಮ್ಮ ದೃಷ್ಟಿ ನಮ್ಮ ದೀರ್ಘಕಾಲೀನ ಆಕಾಂಕ್ಷೆಗಳನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ. AIET ನಲ್ಲಿ, ಹೊಂದಿಕೊಳ್ಳುವ, ಅಂತರ್ಗತ ಮತ್ತು ಭವಿಷ್ಯಕ್ಕೆ ಸಿದ್ಧವಾಗಿರುವ ಪರಿವರ್ತಕ ಶಿಕ್ಷಣವನ್ನು ನೀಡುವ ಗುರಿಯನ್ನು ನಾವು ಹೊಂದಿದ್ದೇವೆ. ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಇಂದಿನ ಸವಾಲುಗಳಿಗೆ ಸಿದ್ಧಪಡಿಸುವುದಲ್ಲದೆ ನಾಳೆಯನ್ನು ರೂಪಿಸಲು ಅವರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದರಲ್ಲಿ ನಾವು ನಂಬುತ್ತೇವೆ.",
    vm_mission_title: "AIET ಯ ಧ್ಯೇಯ",
    vm_mission_points: [
      "ವಿದ್ಯಾರ್ಥಿ ಸಮುದಾಯಕ್ಕೆ ಜ್ಞಾನ, ಸೃಜನಶೀಲತೆ ಮತ್ತು ನೈತಿಕತೆಯನ್ನು ಅಳವಡಿಸಿಕೊಳ್ಳಲು ಗುಣಮಟ್ಟದ ತಾಂತ್ರಿಕ ಶಿಕ್ಷಣವನ್ನು ನೀಡುವುದು.",
      "ಪರಿವರ್ತಕ ಶಿಕ್ಷಣದ ಮೂಲಕ ಅತ್ಯುತ್ತಮ ಎಂಜಿನಿಯರಿಂಗ್ ಅಭ್ಯಾಸಗಳನ್ನು ಅಳವಡಿಸುವುದು.",
      "ಕ್ರಿಯಾತ್ಮಕ ಕೈಗಾರಿಕಾ ಸನ್ನಿವೇಶಕ್ಕಾಗಿ ಜ್ಞಾನವುಳ್ಳ ವ್ಯಕ್ತಿಯನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸುವುದು.",
      "ಸಮಾಜದ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸುವ ಸಲುವಾಗಿ ಸಂಶೋಧನೆ, ಉದ್ಯಮಶೀಲತಾ ಕೌಶಲ್ಯಗಳು ಮತ್ತು ಮಾನವ ಮೌಲ್ಯಗಳನ್ನು ಅಳವಡಿಸುವುದು."
    ],
    vm_mission_desc: "ನಮ್ಮ ಧ್ಯೇಯವು ನಮ್ಮ ದೃಷ್ಟಿಯನ್ನು ಸಾಧಿಸುವ ಮಾರ್ಗವನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ವಿವರಿಸುತ್ತದೆ. ಗುಣಮಟ್ಟ-ಚಾಲಿತ ತಾಂತ್ರಿಕ ಶಿಕ್ಷಣ ಮತ್ತು ನೈತಿಕ ಅಭಿವೃದ್ಧಿಯ ಮೂಲಕ, ನಾವು ವೃತ್ತಿಪರರನ್ನು ಮಾತ್ರವಲ್ಲದೆ ಜವಾಬ್ದಾರಿಯುತ ನಾಗರಿಕರನ್ನೂ ನಿರ್ಮಿಸುತ್ತೇವೆ.",

    // Footer
    foot_title: "ಆಳ್ವಾಸ್ ಇಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ಸಂಸ್ಥೆ",
    foot_subtitle: "(ಒಂದು ಸ್ವಾಯತ್ತ ಸಂಸ್ಥೆ)",
    foot_address: "ಶೋಭಾವನ ಕ್ಯಾಂಪಸ್, ಮಿಜಾರ್, ಮೂಡುಬಿದಿರೆ, ದಕ್ಷಿಣ ಕನ್ನಡ, ಕರ್ನಾಟಕ - 574225",
    foot_copyright: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",

    // Vision & Mission
    vm_title: "AIET ದೃಷ್ಟಿ ಮತ್ತು ಧ್ಯೇಯ ಹೇಳಿಕೆ",
    vm_subtitle: "ಸಾಂಸ್ಥಿಕ ಶ್ರೇಷ್ಠತೆಯನ್ನು ಮುನ್ನಡೆಸುವ ಮಾರ್ಗದರ್ಶಿ ತತ್ವಗಳು.",
    vm_vision_title: "AIET ಯ ದೃಷ್ಟಿ",
    vm_vision_quote: "\"ಸಮುದಾಯದ ವಿಕಸನಗೊಳ್ಳುತ್ತಿರುವ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸಲು ಕೌಶಲ್ಯಗಳನ್ನು ಹೆಚ್ಚಿಸುವ ಮೂಲಕ ಎಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್‌ನಲ್ಲಿ ಶ್ರೇಷ್ಠತೆಯನ್ನು ಅನುಸರಿಸುವ ಮೂಲಕ ಪರಿವರ್ತಕ ಶಿಕ್ಷಣ.\"",
    vm_vision_desc: "ನಮ್ಮ ದೃಷ್ಟಿ ನಮ್ಮ ದೀರ್ಘಕಾಲೀನ ಆಕಾಂಕ್ಷೆಗಳನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ. AIET ನಲ್ಲಿ, ಹೊಂದಿಕೊಳ್ಳುವ, ಅಂತರ್ಗತ ಮತ್ತು ಭವಿಷ್ಯಕ್ಕೆ ಸಿದ್ಧವಾಗಿರುವ ಪರಿವರ್ತಕ ಶಿಕ್ಷಣವನ್ನು ನೀಡುವ ಗುರಿಯನ್ನು ನಾವು ಹೊಂದಿದ್ದೇವೆ. ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಇಂದಿನ ಸವಾಲುಗಳಿಗೆ ಸಿದ್ಧಪಡಿಸುವುದಲ್ಲದೆ ನಾಳೆಯನ್ನು ರೂಪಿಸಲು ಅವರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದರಲ್ಲಿ ನಾವು ನಂಬುತ್ತೇವೆ.",
    vm_mission_title: "AIET ಯ ಧ್ಯೇಯ",
    vm_mission_points: [
      "ವಿದ್ಯಾರ್ಥಿ ಸಮುದಾಯಕ್ಕೆ ಜ್ಞಾನ, ಸೃಜನಶೀಲತೆ ಮತ್ತು ನೈತಿಕತೆಯನ್ನು ಅಳವಡಿಸಿಕೊಳ್ಳಲು ಗುಣಮಟ್ಟದ ತಾಂತ್ರಿಕ ಶಿಕ್ಷಣವನ್ನು ನೀಡುವುದು.",
      "ಪರಿವರ್ತಕ ಶಿಕ್ಷಣದ ಮೂಲಕ ಅತ್ಯುತ್ತಮ ಎಂಜಿನಿಯರಿಂಗ್ ಅಭ್ಯಾಸಗಳನ್ನು ಅಳವಡಿಸುವುದು.",
      "ಕ್ರಿಯಾತ್ಮಕ ಕೈಗಾರಿಕಾ ಸನ್ನಿವೇಶಕ್ಕಾಗಿ ಜ್ಞಾನವುಳ್ಳ ವ್ಯಕ್ತಿಯನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸುವುದು.",
      "ಸಮಾಜದ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸುವ ಸಲುವಾಗಿ ಸಂಶೋಧನೆ, ಉದ್ಯಮಶೀಲತಾ ಕೌಶಲ್ಯಗಳು ಮತ್ತು ಮಾನವ ಮೌಲ್ಯಗಳನ್ನು ಅಳವಡಿಸುವುದು."
    ],
    vm_mission_desc: "ನಮ್ಮ ಧ್ಯೇಯವು ನಮ್ಮ ದೃಷ್ಟಿಯನ್ನು ಸಾಧಿಸುವ ಮಾರ್ಗವನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ವಿವರಿಸುತ್ತದೆ. ಗುಣಮಟ್ಟ-ಚಾಲಿತ ತಾಂತ್ರಿಕ ಶಿಕ್ಷಣ ಮತ್ತು ನೈತಿಕ ಅಭಿವೃದ್ಧಿಯ ಮೂಲಕ, ನಾವು ವೃತ್ತಿಪರರನ್ನು ಮಾತ್ರವಲ್ಲದೆ ಜವಾಬ್ದಾರಿಯುತ ನಾಗರಿಕರನ್ನೂ ನಿರ್ಮಿಸುತ್ತೇವೆ.",

    // Footer
    foot_title: "ಆಳ್ವಾಸ್ ಇಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ಸಂಸ್ಥೆ",
    foot_subtitle: "(ಒಂದು ಸ್ವಾಯತ್ತ ಸಂಸ್ಥೆ)",
    foot_address: "ಶೋಭಾವನ ಕ್ಯಾಂಪಸ್, ಮಿಜಾರ್, ಮೂಡುಬಿದಿರೆ, ದಕ್ಷಿಣ ಕನ್ನಡ, ಕರ್ನಾಟಕ - 574225",

    // Virtual Tour
    vt_title: "ಸಂವಾದಾತ್ಮಕ ವರ್ಚುವಲ್ ಟೂರ್",
    vt_subtitle: "ಕ್ಯಾಂಪಸ್ ಅನ್ನು 360° ಯಲ್ಲಿ ಅನ್ವೇಷಿಸಲು ವೀಕ್ಷಣೆ ಪೋರ್ಟ್ ಒಳಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ಎಳೆಯಿರಿ",
    vt_loc: "ಸ್ಥಳಗಳು",
    vt_loc_gate: "ಮುಖ್ಯ ಕ್ಯಾಂಪಸ್ ಪ್ರವೇಶದ್ವಾರ",
    vt_loc_lib: "ಕೇಂದ್ರ ಗ್ರಂಥಾಲಯ ಸಭಾಂಗಣ",

    // Admission
    adm_portal: "ಪ್ರವೇಶ ಪೋರ್ಟಲ್",
    adm_sub_desc: "ನಿಮ್ಮ ಕೋರ್ಸ್‌ ಸೀಟು ಕಾಯ್ದಿರಿಸಿಕೊಳ್ಳಿ ಅಥವಾ ಆಡಳಿತ ಸಭೆಯ ಸಮಯವನ್ನು ವಿನಂತಿಸಿ.",
    adm_req: "AIET ಪ್ರವೇಶ ಅವಶ್ಯಕತೆಗಳು",
    adm_req_succ: "ಸೀಟನ್ನು ಯಶಸ್ವಿಯಾಗಿ ವಿನಂತಿಸಲಾಗಿದೆ!",
    adm_phys: "ಕ್ಯಾಂಪಸ್ ನೇಮಕಾತಿಗಳು",
    adm_phys_succ: "ಭೌತಿಕ ಸ್ಲಾಟ್ ನೋಂದಾಯಿಸಲಾಗಿದೆ!",
    adm_rem: "ರಿಮೋಟ್ ವೀಡಿಯೊ ಕೌನ್ಸೆಲಿಂಗ್",
    adm_rem_succ: "ವರ್ಚುವಲ್ ಕೌನ್ಸೆಲಿಂಗ್ ಹೊಂದಿಸಲಾಗಿದೆ!",
    adm_tab_1: "1. ಆನ್‌ಲೈನ್ ಸೀಟು ಬುಕಿಂಗ್",
    adm_tab_2: "2. ಆಫ್‌ಲೈನ್ ಕ್ಯಾಂಪಸ್ ಕೌನ್ಸೆಲಿಂಗ್",
    adm_tab_3: "3. ಆನ್‌ಲೈನ್ ಕೌನ್ಸೆಲಿಂಗ್ (ರಿಮೋಟ್)",
    adm_elig_title: "ಶೈಕ್ಷಣಿಕ ಅರ್ಹತೆ",
    adm_elig_desc: "10+2 / PUC ಯಲ್ಲಿ ಭೌತಶಾಸ್ತ್ರ ಮತ್ತು ಗಣಿತವನ್ನು ಕಡ್ಡಾಯ ವಿಷಯಗಳಾಗಿ ಹೊಂದಿರುವ ಕನಿಷ್ಠ 45% ಅಂಕಗಳು.",
    adm_score_title: "ಪ್ರವೇಶ ಅಂಕಪಟ್ಟಿಗಳು",
    adm_score_desc: "KCET, COMEDK, ಅಥವಾ JEE ಮೈನ್ ಆಯ್ಕೆಗಳಿಂದ ಮಾನ್ಯವಾದ ಮೆಟ್ರಿಕ್‌ಗಳು.",
    adm_mgt_title: "ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಕೋಟಾ",
    adm_mgt_desc: "ಕನಿಷ್ಠ ಶೈಕ್ಷಣಿಕ ಮಾನದಂಡಗಳನ್ನು ಪೂರೈಸುವ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ನೇರ ಪ್ರವೇಶ ಲಭ್ಯವಿದೆ.",
    adm_snq_title: "SNQ ಕೋಟಾ",
    adm_snq_desc: "ಆರ್ಥಿಕವಾಗಿ ದುರ್ಬಲ ವರ್ಗಗಳ ಅರ್ಹ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಸೂಪರ್ನ್ಯೂಮರರಿ ಕೋಟಾ ಸೀಟುಗಳು.",
    adm_view_syl: "ಪಠ್ಯಕ್ರಮವನ್ನು ವೀಕ್ಷಿಸಿ",
    adm_form_name: "ಅರ್ಜಿದಾರರ ಪೂರ್ಣ ಹೆಸರು",
    adm_form_email: "ಇಮೇಲ್ ವಿಳಾಸ",
    adm_form_phone: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    adm_form_branch: "ಅಪೇಕ್ಷಿತ ಕಾರ್ಯಕ್ರಮ / ಶಾಖೆ",
    adm_btn_confirm: "ಆನ್‌ಲೈನ್ ಸೀಟು ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ",
    adm_form_desk: "ಡೆಸ್ಕ್ ಪ್ರಾಧಿಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    adm_admin_officer_desk: "ಆಡಳಿತಾಧಿಕಾರಿ (ಶ್ರೀ ನಿಖಿಲ್ ಆಳ್ವ)",
    adm_admin_officer_title: "ಆಡಳಿತಾಧಿಕಾರಿ",
    adm_admin_officer_name: "(ಶ್ರೀ ನಿಖಿಲ್ ಆಳ್ವ)",
    adm_admission_officer_desk: "ಪ್ರವೇಶಾಧಿಕಾರಿ (ಶ್ರೀ ತಿಲಕ್)",
    adm_admission_officer_title: "ಪ್ರವೇಶಾಧಿಕಾರಿ",
    adm_admission_officer_name: "(ಶ್ರೀ ತಿಲಕ್)",
    adm_form_date: "ನೇಮಕಾತಿ ದಿನಾಂಕ",
    adm_btn_token: "ಪ್ರವೇಶ ಟೋಕನ್ ರಚಿಸಿ",
    adm_form_email_link: "ಇಮೇಲ್ ವಿಳಾಸ (ಆಹ್ವಾನ ಲಿಂಕ್‌ಗಾಗಿ)",
    adm_form_target: "ಗುರಿ ಶಾಖೆ",
    adm_form_pref_date: "ಆದ್ಯತೆಯ ಸಮಾಲೋಚನೆ ದಿನಾಂಕ",
    adm_btn_remote: "ರಿಮೋಟ್ ಸಮಾಲೋಚನೆಗಾಗಿ ವಿನಂತಿಸಿ",
    adm_applicant_name: "ಅರ್ಜಿದಾರರ ಹೆಸರು:",
    adm_selected_branch: "ಆಯ್ಕೆಮಾಡಿದ ಶಾಖೆ:",
    adm_status_label: "ಸ್ಥಿತಿ:",
    adm_provisionally_saved: "ಹಂತ-ಹಂತವಾಗಿ ಉಳಿಸಲಾಗಿದೆ",
    adm_desk_alert: "ಡೆಸ್ಕ್ ಎಚ್ಚರಿಕೆ:",
    adm_live_queue: "ಪ್ರಸ್ತುತ ನಿರೀಕ್ಷಣಾ ಸಾಲು:",
    adm_virtual_route: "ವರ್ಚುವಲ್ ಡೆಸ್ಕ್ ಮಾರ್ಗ:",
    adm_meet_room: "ಲೈವ್ ಗೂಗಲ್ ಮೀಟ್ ರೂಮ್ ಸೇರಿ",
    adm_principal_desk: "ಪ್ರಾಂಶುಪಾಲರ ಡೆಸ್ಕ್",
    adm_ao_desk: "ಪ್ರವೇಶಾತಿ ಅಧಿಕಾರಿ (AO)",
    adm_opt_ug_group: "ಪದವಿಪೂರ್ವ (UG) - B.E.",
    adm_opt_pg_group: "ಸ್ನಾತಕೋತ್ತರ (PG)",

    // PG Admission Specific
    pg_adm_portal: "ಸ್ನಾತಕೋತ್ತರ (PG) ಪ್ರವೇಶ ಪೋರ್ಟಲ್",
    pg_adm_subtitle: "ನಿಮ್ಮ MBA ಸೀಟು ಹಂಚಿಕೆಯನ್ನು ಭದ್ರಪಡಿಸಿಕೊಳ್ಳಿ ಅಥವಾ ಆಡಳಿತಾತ್ಮಕ ಸಭೆಯ ಸ್ಲಾಟ್‌ಗೆ ವಿನಂತಿಸಿ.",
    pg_adm_elig_title: "ಅರ್ಹತೆ",
    pg_adm_elig_desc: "ಯಾವುದೇ ವಿಭಾಗದಲ್ಲಿ ಕನಿಷ್ಠ 50% ಅಂಕಗಳೊಂದಿಗೆ (ಭಾಷೆಗಳನ್ನು ಒಳಗೊಂಡಂತೆ) ಪದವಿ ಪಡೆದಿರಬೇಕು. ಅಂತಿಮ ವರ್ಷದ ವಿದ್ಯಾರ್ಥಿಗಳೂ ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು.",
    pg_adm_score_title: "ಪ್ರವೇಶ ಪರೀಕ್ಷೆಗಳು",
    pg_adm_score_desc: "CAT, MAT, KMAT ಅಥವಾ PGCET ಪರೀಕ್ಷೆಗಳ ಮಾನ್ಯ ಅಂಕಗಳನ್ನು ಸಲ್ಲಿಸಿ.",
    pg_adm_sel_title: "ಆಯ್ಕೆ ಪ್ರಕ್ರಿಯೆ",
    pg_adm_sel_desc: "ಆಯ್ಕೆಯಾದ ಅಭ್ಯರ್ಥಿಗಳನ್ನು ಗುಂಪು ಚರ್ಚೆ (GD) ಮತ್ತು ವೈಯಕ್ತಿಕ ಸಂದರ್ಶನಕ್ಕೆ (PI) ಆಹ್ವಾನಿಸಲಾಗುತ್ತದೆ.",
    pg_adm_about_btn: "MBA ಬಗ್ಗೆ",
    pg_adm_about_alert: "MBA ಕಾರ್ಯಕ್ರಮದ ವಿವರಗಳು:\n- 2 ವರ್ಷದ ಪೂರ್ಣಾವಧಿ\n- ಉಭಯ ವಿಶೇಷತೆಗಳು\n- 100% ಉದ್ಯೋಗ ಸಹಾಯ"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Set default language to English ('en')
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
